In [1]:
# Hücre 1
import os
import io
import csv
import time
import requests
import pandas as pd
from datetime import datetime, timedelta
from dateutil import parser as dateparse
from tqdm import tqdm

# Kayıt klasörü
os.makedirs('data', exist_ok=True)

In [3]:
# Hücre A
import os
import pandas as pd
from datetime import datetime, timedelta

# Çalışma dizini: repo kökünde olduğunu varsayıyoruz
print("Çalışma dizini:", os.getcwd())

# Dosya yolları
FEED_CSV = "feed.csv"
ARCHIVE_DIR = "data"   # yukarıdaki adımla archive buraya çıkarıldıysa

Çalışma dizini: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma

In [9]:
import os

# 1. Şu anki konumu görelim
print("Başlangıç klasörü:", os.getcwd())

# 2. Doğru klasöre geçelim
os.chdir(r"C:\Users\elifo\OneDrive\academic")

# 3. Kontrol edelim
print("Yeni klasör:", os.getcwd())

# 4. Dosyalar burada mı?
print("feed.csv var mı?", os.path.exists("feed.csv"))
print("archive.tar.gz var mı?", os.path.exists("archive.tar.gz"))

Başlangıç klasörü: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma
Yeni klasör: C:\Users\elifo\OneDrive\academic
feed.csv var mı? True
archive.tar.gz var mı? True

In [10]:
import pandas as pd

# feed.csv'yi oku
df_feed = pd.read_csv("feed.csv", dtype=str, low_memory=False, nrows=10)

# Kolonları ve ilk satırları göster
print("Kolonlar:", df_feed.columns.tolist())
df_feed.head()

Kolonlar: ['url', 'brand', 'ip', 'asn', 'asn_name', 'country_code', 'country_name', 'tld', 'discover_time', 'family_id', 'host', 'isotime', 'page_language', 'ssl_cert_issued_by', 'ssl_cert_issued_to', 'ssl_cert_serial', 'is_spear', 'sector']

,url,brand,ip,asn,asn_name,country_code,country_name,tld,discover_time,family_id,host,isotime,page_language,ssl_cert_issued_by,ssl_cert_issued_to,ssl_cert_serial,is_spear,sector
0,https://www.roblox.tc/games/2753915549/BOMB-Bl...,Generic/Spear Phishing,179.43.188.90,AS51852,Private Layer INC,CH,Switzerland,tc,22-10-2025 12:36:42 UTC,b166b1ef93690074336a083420eaa36e,www.roblox.tc,2025-10-22T12:36:42Z,en:0.9999961578445512,Let's Encrypt,roblox.tc,05D2FBB15D5F198D63E5E1A1224915D7F709,False,NaN
1,http://www.whatgood.vip/,WhatsApp,47.236.25.230,AS45102,"Alibaba (US) Technology Co., Ltd.",SG,Singapore,vip,22-10-2025 12:36:36 UTC,38a0c75ce6c47735ac673fb722322c1a,www.whatgood.vip,2025-10-22T12:36:36Z,NaN,Let's Encrypt,www.whatgood.vip,05047DE49010ACECF485A846C7A64166F22B,False,Social Networking
2,http://www.b45030.com/,Bet365,206.119.83.71,AS140227,"Hong Kong Communications International Co., Li...",HK,Hong Kong,com,22-10-2025 12:35:33 UTC,2fd6c9ba8c5b9bcf2e46a42d8ae72081,www.b45030.com,2025-10-22T12:35:33Z,NaN,Let's Encrypt,www.b45030.com,06BDF6C9CD5A8FEE514455F74C7E4E0F72D6,False,Gambling
3,http://j209j.xyz/,Bet365,122.114.10.149,AS4837,CHINA UNICOM China169 Backbone,CN,China,xyz,22-10-2025 12:32:51 UTC,a6933543b809480a645ad313fcb0d1dc,j209j.xyz,2025-10-22T12:32:51Z,NaN,Default Company Ltd,NaN,89796B42E85B2BC4,False,Gambling
4,http://www.buysjzh8787.sbs/,TikTok,137.220.153.16,AS4907,BGPNET PTE. LTD.,HK,Hong Kong,sbs,22-10-2025 12:31:47 UTC,81e80d799d5a0a0bc087e8bca0126c5b,www.buysjzh8787.sbs,2025-10-22T12:31:47Z,NaN,Let's Encrypt,www.seiurutbue.my,0561250320846BB6BC3AD24FADC325E3E82B,False,Social Networking

In [11]:
import pandas as pd

df = pd.read_csv("feed.csv", dtype=str, low_memory=False)
print("Toplam kayıt:", len(df))
df.head(5)

Toplam kayıt: 1638

,url,brand,ip,asn,asn_name,country_code,country_name,tld,discover_time,family_id,host,isotime,page_language,ssl_cert_issued_by,ssl_cert_issued_to,ssl_cert_serial,is_spear,sector
0,https://www.roblox.tc/games/2753915549/BOMB-Bl...,Generic/Spear Phishing,179.43.188.90,AS51852,Private Layer INC,CH,Switzerland,tc,22-10-2025 12:36:42 UTC,b166b1ef93690074336a083420eaa36e,www.roblox.tc,2025-10-22T12:36:42Z,en:0.9999961578445512,Let's Encrypt,roblox.tc,05D2FBB15D5F198D63E5E1A1224915D7F709,False,NaN
1,http://www.whatgood.vip/,WhatsApp,47.236.25.230,AS45102,"Alibaba (US) Technology Co., Ltd.",SG,Singapore,vip,22-10-2025 12:36:36 UTC,38a0c75ce6c47735ac673fb722322c1a,www.whatgood.vip,2025-10-22T12:36:36Z,NaN,Let's Encrypt,www.whatgood.vip,05047DE49010ACECF485A846C7A64166F22B,False,Social Networking
2,http://www.b45030.com/,Bet365,206.119.83.71,AS140227,"Hong Kong Communications International Co., Li...",HK,Hong Kong,com,22-10-2025 12:35:33 UTC,2fd6c9ba8c5b9bcf2e46a42d8ae72081,www.b45030.com,2025-10-22T12:35:33Z,NaN,Let's Encrypt,www.b45030.com,06BDF6C9CD5A8FEE514455F74C7E4E0F72D6,False,Gambling
3,http://j209j.xyz/,Bet365,122.114.10.149,AS4837,CHINA UNICOM China169 Backbone,CN,China,xyz,22-10-2025 12:32:51 UTC,a6933543b809480a645ad313fcb0d1dc,j209j.xyz,2025-10-22T12:32:51Z,NaN,Default Company Ltd,NaN,89796B42E85B2BC4,False,Gambling
4,http://www.buysjzh8787.sbs/,TikTok,137.220.153.16,AS4907,BGPNET PTE. LTD.,HK,Hong Kong,sbs,22-10-2025 12:31:47 UTC,81e80d799d5a0a0bc087e8bca0126c5b,www.buysjzh8787.sbs,2025-10-22T12:31:47Z,NaN,Let's Encrypt,www.seiurutbue.my,0561250320846BB6BC3AD24FADC325E3E82B,False,Social Networking

In [14]:
from datetime import datetime

for col in ["discover_time", "isotime"]:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce', dayfirst=True)


df[["discover_time", "isotime"]].head()

              discover_time                   isotime
0 2025-10-22 12:36:42+00:00 2025-10-22 12:36:42+00:00
1 2025-10-22 12:36:36+00:00 2025-10-22 12:36:36+00:00
2 2025-10-22 12:35:33+00:00 2025-10-22 12:35:33+00:00
3 2025-10-22 12:32:51+00:00 2025-10-22 12:32:51+00:00
4 2025-10-22 12:31:47+00:00 2025-10-22 12:31:47+00:00

In [16]:
from datetime import datetime, timedelta, timezone

# Son 1 yıl cutoff (UTC farkıyla)
cutoff = datetime.now(timezone.utc) - timedelta(days=365)

# isotime varsa UTC uyumlu filtreleme
if "isotime" in df.columns:
    df_recent = df[df["isotime"] >= cutoff].copy()
elif "discover_time" in df.columns:
    df_recent = df[df["discover_time"] >= cutoff].copy()
else:
    df_recent = df.copy()

print("Son 1 yıl kaydı:", len(df_recent))
df_recent.head()

Son 1 yıl kaydı: 1638

,url,brand,ip,asn,asn_name,country_code,country_name,tld,discover_time,family_id,host,isotime,page_language,ssl_cert_issued_by,ssl_cert_issued_to,ssl_cert_serial,is_spear,sector
0,https://www.roblox.tc/games/2753915549/BOMB-Bl...,Generic/Spear Phishing,179.43.188.90,AS51852,Private Layer INC,CH,Switzerland,tc,2025-10-22 12:36:42+00:00,b166b1ef93690074336a083420eaa36e,www.roblox.tc,2025-10-22 12:36:42+00:00,en:0.9999961578445512,Let's Encrypt,roblox.tc,05D2FBB15D5F198D63E5E1A1224915D7F709,False,NaN
1,http://www.whatgood.vip/,WhatsApp,47.236.25.230,AS45102,"Alibaba (US) Technology Co., Ltd.",SG,Singapore,vip,2025-10-22 12:36:36+00:00,38a0c75ce6c47735ac673fb722322c1a,www.whatgood.vip,2025-10-22 12:36:36+00:00,NaN,Let's Encrypt,www.whatgood.vip,05047DE49010ACECF485A846C7A64166F22B,False,Social Networking
2,http://www.b45030.com/,Bet365,206.119.83.71,AS140227,"Hong Kong Communications International Co., Li...",HK,Hong Kong,com,2025-10-22 12:35:33+00:00,2fd6c9ba8c5b9bcf2e46a42d8ae72081,www.b45030.com,2025-10-22 12:35:33+00:00,NaN,Let's Encrypt,www.b45030.com,06BDF6C9CD5A8FEE514455F74C7E4E0F72D6,False,Gambling
3,http://j209j.xyz/,Bet365,122.114.10.149,AS4837,CHINA UNICOM China169 Backbone,CN,China,xyz,2025-10-22 12:32:51+00:00,a6933543b809480a645ad313fcb0d1dc,j209j.xyz,2025-10-22 12:32:51+00:00,NaN,Default Company Ltd,NaN,89796B42E85B2BC4,False,Gambling
4,http://www.buysjzh8787.sbs/,TikTok,137.220.153.16,AS4907,BGPNET PTE. LTD.,HK,Hong Kong,sbs,2025-10-22 12:31:47+00:00,81e80d799d5a0a0bc087e8bca0126c5b,www.buysjzh8787.sbs,2025-10-22 12:31:47+00:00,NaN,Let's Encrypt,www.seiurutbue.my,0561250320846BB6BC3AD24FADC325E3E82B,False,Social Networking

In [17]:
# Hücre 1: klasör oluşturma ve df_recent kaydetme
import os

base_folder = r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma"
openphish_folder = os.path.join(base_folder, "Phishingdata_openphish")
phishtank_folder = os.path.join(base_folder, "Phishingdata_phishtank")

os.makedirs(openphish_folder, exist_ok=True)
os.makedirs(phishtank_folder, exist_ok=True)

print("Klasörler hazır:")
print(" - OpenPhish hedef:", openphish_folder)
print(" - PhishTank hedef:", phishtank_folder)

# df_recent mevcut mu kontrol et
if 'df_recent' not in globals():
    raise RuntimeError("df_recent bulunamadı. Önce son 1 yıl filtresini uyguladığın hücreyi çalıştır.")
    
# Kaydet (CSV ve Parquet)
openphish_csv = os.path.join(openphish_folder, "Phishingdata_openphish_last1y.csv")
openphish_parquet = os.path.join(openphish_folder, "Phishingdata_openphish_last1y.parquet")

df_recent.to_csv(openphish_csv, index=False)
try:
    df_recent.to_parquet(openphish_parquet, index=False)
    print("Saved CSV + Parquet.")
except Exception as e:
    print("Parquet kaydetme başarısız (muhtemelen pyarrow yok). Sadece CSV kaydedildi. Hata:", e)

print("OpenPhish son 1 yıl satır sayısı:", len(df_recent))
print("Kaydedildi:", openphish_csv)

Klasörler hazır:
 - OpenPhish hedef: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_openphish
 - PhishTank hedef: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank
Parquet kaydetme başarısız (muhtemelen pyarrow yok). Sadece CSV kaydedildi. Hata: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
OpenPhish son 1 yıl satır sayısı: 1638
Kaydedildi: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_openphish\Phishingdata_openphish_last1y.csv

In [18]:
# Hücre 3: PhishTank online-valid.csv indirme (streaming)
import requests
import os
phishtank_url = "http://data.phishtank.com/data/online-valid.csv"  # yaygın public link
out_path = os.path.join(phishtank_folder, "online-valid.csv")

print("İndiriliyor (streaming) ->", out_path)
try:
    with requests.get(phishtank_url, stream=True, timeout=120) as r:
        r.raise_for_status()
        with open(out_path, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
    print("İndirme tamamlandı.")
except requests.exceptions.HTTPError as e:
    print("HTTP hata:", e)
    print("Eğer 403/401/429 alıyorsan PhishTank hesabına giriş gerekebilir veya indirme linki değişmiş olabilir.")
    print("Manuel alternatif: https://www.phishtank.com/ sitesinden 'Download' veya 'Data' bölümünden CSV indirip", phishtank_folder, "içine koy.")
except Exception as e:
    print("İndirme sırasında hata:", e)

İndiriliyor (streaming) -> C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank\online-valid.csv
HTTP hata: 404 Client Error: Not Found for url: https://cdn.phishtank.com/datadumps/verified_online.csv?Expires=1761138340&Signature=PF~x1wTc7O9wXfsrPoYotL4bYF3rifwkSY2NvM7cOcuMH25o1-bmKn8ydJ4ktInJmKYKgo-ubJ3bsk6TKNcrohLBsu-udglVWHSfQXIkjH1mL5hZO3RFlYFaRPemErj31Xj9klo-tNVHmCCCT-tCLWrIkSjGA01zLc5b2trUQTLlWDmqz80i4nxU2Pjto7gQVSG9F3kcOJfBbyVJalMzxUOsaeGO-3rv2sNgtDMUE1DSS~YqH9v4ZeD4WO1adJ9POKlV4UdPktZSfGrlBbf6uqRtdd60m5ebti3lEqHQaK1J~11x1WOV7pys6DFXbxuYqDXbaoIEGrpywS4ihzxCpw__&Key-Pair-Id=APKAILB45UG3RB4CSOJA
Eğer 403/401/429 alıyorsan PhishTank hesabına giriş gerekebilir veya indirme linki değişmiş olabilir.
Manuel alternatif: https://www.phishtank.com/ sitesinden 'Download' veya 'Data' bölümünden CSV indirip C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank içine koy.

In [21]:
import os
import requests

# Klasörün
base_folder = r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank"
os.makedirs(base_folder, exist_ok=True)

# ---- PhishTank erişim bilgileri ----
# Eğer hesabın varsa buraya kendi APP_KEY'ini yaz (örnek: "ab1234567890abcdef...")
APP_KEY = ""  # Boş bırak, eğer yoksa anonim deneme yapar

if APP_KEY.strip():
    url = f"https://data.phishtank.com/data/{APP_KEY}/online-valid.csv"
else:
    url = "http://data.phishtank.com/data/online-valid.csv"

out_path = os.path.join(base_folder, "online-valid.csv")

print(f"📥 İndiriliyor: {url}")

try:
    with requests.get(url, stream=True, timeout=180) as r:
        print("HTTP Durumu:", r.status_code)
        if r.status_code != 200:
            raise Exception("İndirme başarısız! Muhtemelen APP_KEY veya erişim kısıtlı.")
        total = 0
        with open(out_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
                    total += len(chunk)
        print(f"✅ PhishTank CSV başarıyla indirildi: {out_path}")
        print(f"   Boyut: {total / (1024*1024):.2f} MB")
except Exception as e:
    print("⚠️ Hata:", e)
    print("\nEğer 403 (Forbidden) aldıysan:")
    print("👉 1. https://www.phishtank.com/developer_info.php adresine gir.")
    print("👉 2. Ücretsiz hesap oluştur.")
    print("👉 3. Giriş yaptıktan sonra sayfada göreceğin bağlantı:")
    print("     https://data.phishtank.com/data/<APP_KEY>/online-valid.csv")
    print("   içindeki <APP_KEY> değerini kopyalayıp yukarıdaki APP_KEY değişkenine yapıştır.")

📥 İndiriliyor: http://data.phishtank.com/data/online-valid.csv
HTTP Durumu: 200
✅ PhishTank CSV başarıyla indirildi: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank\online-valid.csv
   Boyut: 9.41 MB

In [22]:
import os
print(os.listdir(r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank"))

['online-valid.csv']

In [23]:
RAW_DIR = r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank"
pt_path = os.path.join(RAW_DIR, "online-valid.csv")

In [24]:
if os.path.exists(pt_path):
    print("✅ Dosya bulundu:", pt_path)
else:
    print("❌ Hâlâ bulunamadı.")

✅ Dosya bulundu: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank\online-valid.csv

In [25]:
import os
import pandas as pd
from datetime import datetime, timedelta, timezone
from urllib.parse import urlparse
import re

# ---- Klasör ve dosya yolu ----
base_folder = r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank"
pt_csv = os.path.join(base_folder, "online-valid.csv")

# ---- 1️⃣ CSV'yi oku (önizleme) ----
print("📄 Okunuyor:", pt_csv)
tmp = pd.read_csv(pt_csv, dtype=str, nrows=5, low_memory=False)
print("Kolonlar:", tmp.columns.tolist())

# ---- 2️⃣ Tarih sütununu otomatik bul ----
possible_date_cols = [c for c in tmp.columns if any(x in c.lower() for x in ["submission", "verified", "date", "time"])]
date_col = possible_date_cols[0] if possible_date_cols else None
print("⏱️ Tarih kolonu:", date_col)

# ---- 3️⃣ Tüm dosyayı parçalı oku ve son 1 yıl filtrele ----
cutoff = datetime.now(timezone.utc) - timedelta(days=365)
chunksize = 200_000
kept_chunks = []
total_in = total_kept = 0

for chunk in pd.read_csv(pt_csv, dtype=str, chunksize=chunksize, low_memory=True):
    total_in += len(chunk)
    if date_col:
        chunk[date_col + "_parsed"] = pd.to_datetime(chunk[date_col], errors="coerce", utc=True)
        sel = chunk[chunk[date_col + "_parsed"] >= cutoff]
    else:
        sel = chunk.copy()
    if not sel.empty:
        kept_chunks.append(sel)
        total_kept += len(sel)

print(f"Toplam {total_in} satır okundu; son 1 yılda {total_kept} kayıt bulundu.")

if kept_chunks:
    df_pt_recent = pd.concat(kept_chunks, ignore_index=True)
else:
    df_pt_recent = pd.DataFrame()

# ---- 4️⃣ URL sütununu tespit et ----
if not df_pt_recent.empty:
    possible_url_cols = [c for c in df_pt_recent.columns if any(k in c.lower() for k in ["url", "link", "uri"])]
    url_col = possible_url_cols[0] if possible_url_cols else df_pt_recent.columns[0]
    print("🔗 URL kolonu:", url_col)
else:
    print("⚠️ Hiç kayıt bulunamadı, URL tespiti atlandı.")
    url_col = None

# ---- 5️⃣ URL normalize + dedupe ----
def normalize_url(u):
    if pd.isna(u): 
        return u
    u = str(u).strip()
    u = re.sub(r"^https?://", "", u, flags=re.I)
    u = u.rstrip("/")
    try:
        p = urlparse("http://" + u)
        host = p.netloc.lower()
        if host.startswith("www."):
            host = host[4:]
        path = p.path.rstrip("/")
        qs = ("?" + p.query) if p.query else ""
        return host + path + qs
    except:
        return u.lower()

if url_col and not df_pt_recent.empty:
    df_pt_recent["url_norm"] = df_pt_recent[url_col].astype(str).apply(normalize_url)
    before = len(df_pt_recent)
    df_pt_recent = df_pt_recent.drop_duplicates(subset=["url_norm"])
    after = len(df_pt_recent)
    print(f"🔄 Tekrarlar kaldırıldı: {before} → {after}")

# ---- 6️⃣ Kaydet ----
out_csv = os.path.join(base_folder, "Phishingdata_phishtank_last1y.csv")
df_pt_recent.to_csv(out_csv, index=False)
print(f"✅ Kaydedildi: {out_csv}")
print(f"Satır sayısı: {len(df_pt_recent)}")

📄 Okunuyor: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank\online-valid.csv
Kolonlar: ['phish_id', 'url', 'phish_detail_url', 'submission_time', 'verified', 'verification_time', 'online', 'target']
⏱️ Tarih kolonu: submission_time
Toplam 49357 satır okundu; son 1 yılda 22613 kayıt bulundu.
🔗 URL kolonu: url
🔄 Tekrarlar kaldırıldı: 22613 → 22134
✅ Kaydedildi: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_phishtank\Phishingdata_phishtank_last1y.csv
Satır sayısı: 22134

In [26]:
import os
import pandas as pd

# ---- 1️⃣ Dosya yolları ----
base_folder = r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma"
openphish_path = os.path.join(base_folder, "Phishingdata_openphish", "Phishingdata_openphish_last1y.csv")
phishtank_path = os.path.join(base_folder, "Phishingdata_phishtank", "Phishingdata_phishtank_last1y.csv")
combined_path = os.path.join(base_folder, "Phishingdata_all_phishdata.csv")

# ---- 2️⃣ Dosyaları oku (yalnızca url kolonları) ----
def load_urls(path):
    if not os.path.exists(path):
        print(f"⚠️ Dosya bulunamadı: {path}")
        return pd.DataFrame(columns=["url"])
    df = pd.read_csv(path, dtype=str, usecols=lambda c: "url" in c.lower(), low_memory=False)
    print(f"📄 {os.path.basename(path)} yüklendi. Satır sayısı: {len(df)}")
    # Kolon ismini normalize et
    url_col = [c for c in df.columns if "url" in c.lower()][0]
    df = df.rename(columns={url_col: "url"})
    return df[["url"]]

df_open = load_urls(openphish_path)
df_pt = load_urls(phishtank_path)

# ---- 3️⃣ Birleştir ve tekrarlanan URL’leri kaldır ----
df_all = pd.concat([df_open, df_pt], ignore_index=True)
print(f"\n🔗 Toplam URL sayısı (birleşik): {len(df_all)}")

df_all.drop_duplicates(subset=["url"], inplace=True)
print(f"✅ Tekrarlardan arındırıldı: {len(df_all)} benzersiz URL kaldı.")

# ---- 4️⃣ Kaydet ----
df_all.to_csv(combined_path, index=False)
print(f"💾 Kaydedildi: {combined_path}")

📄 Phishingdata_openphish_last1y.csv yüklendi. Satır sayısı: 1638
📄 Phishingdata_phishtank_last1y.csv yüklendi. Satır sayısı: 22134

🔗 Toplam URL sayısı (birleşik): 23772
✅ Tekrarlardan arındırıldı: 23700 benzersiz URL kaldı.
💾 Kaydedildi: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_all_phishdata.csv

In [27]:
df_check = pd.read_csv(r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_all_phishdata.csv")
print("Toplam URL:", len(df_check))
df_check.head()

Toplam URL: 23700

                                                 url
0  https://www.roblox.tc/games/2753915549/BOMB-Bl...
1                           http://www.whatgood.vip/
2                             http://www.b45030.com/
3                                  http://j209j.xyz/
4                        http://www.buysjzh8787.sbs/

In [28]:
import pandas as pd
import re
from urllib.parse import urlparse

# Dosya yolu
path = r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_all_phishdata.csv"

# 1️⃣ Dosyayı oku
df = pd.read_csv(path, dtype=str)
print("📄 Orijinal satır sayısı:", len(df))

# 2️⃣ URL normalize fonksiyonu
def normalize_url(u):
    if pd.isna(u):
        return u
    u = str(u).strip()
    # Protokolü kaldır (http / https)
    u = re.sub(r"^https?://", "", u, flags=re.I)
    # Sondaki '/' karakterini kaldır
    u = u.rstrip('/')
    try:
        p = urlparse("http://" + u)
        host = p.netloc.lower()
        if host.startswith("www."):
            host = host[4:]
        path = p.path.rstrip('/')
        qs = ("?" + p.query) if p.query else ""
        return host + path + qs
    except:
        return u.lower()

# 3️⃣ Normalizasyon ve tekrarların kaldırılması
df["url_norm"] = df["url"].apply(normalize_url)
before = len(df)
df_clean = df.drop_duplicates(subset=["url_norm"]).copy()
after = len(df_clean)

print(f"🔄 Tekrarlar kaldırıldı: {before} → {after}")

# 4️⃣ Artık normalize sütuna gerek yoksa silebiliriz
df_clean = df_clean.drop(columns=["url_norm"])

# 5️⃣ Temiz dosyayı kaydet
clean_path = path.replace(".csv", "_clean.csv")
df_clean.to_csv(clean_path, index=False)
print(f"✅ Temiz dosya kaydedildi: {clean_path}")

📄 Orijinal satır sayısı: 23700
🔄 Tekrarlar kaldırıldı: 23700 → 23626
✅ Temiz dosya kaydedildi: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_all_phishdata_clean.csv

In [29]:
df_check = pd.read_csv(r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_all_phishdata_clean.csv")
print("✅ Temiz veri seti satır sayısı:", len(df_check))
df_check.head()

✅ Temiz veri seti satır sayısı: 23626

                                                 url
0  https://www.roblox.tc/games/2753915549/BOMB-Bl...
1                           http://www.whatgood.vip/
2                             http://www.b45030.com/
3                                  http://j209j.xyz/
4                        http://www.buysjzh8787.sbs/

In [30]:
import pandas as pd
import os

# Dosya yolu
path = r"C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_all_phishdata_clean.csv"

# 1️⃣ Dosyayı oku
df = pd.read_csv(path, dtype=str)
print("📄 Başlangıçtaki satır sayısı:", len(df))

# 2️⃣ Boş satır / boş URL kontrolü
# Hem tamamen boş satırları hem de sadece URL sütunu boş olanları bul
empty_rows = df[df.isna().all(axis=1)]
empty_url_rows = df[df["url"].astype(str).str.strip() == ""]

print(f"🔍 Tamamen boş satır sayısı: {len(empty_rows)}")
print(f"🔍 URL sütunu boş olan satır sayısı: {len(empty_url_rows)}")

# 3️⃣ Boş satırları temizle
df = df.dropna(subset=["url"])
df = df[df["url"].astype(str).str.strip() != ""]
df = df.reset_index(drop=True)

print("✅ Temizleme sonrası satır sayısı:", len(df))

# 4️⃣ Label sütunu ekle (tüm satırlar 1 = phishing)
df["label"] = 1

# 5️⃣ Yeni dosya kaydet
out_path = path.replace(".csv", "_labeled.csv")
df.to_csv(out_path, index=False)
print(f"💾 Yeni dosya kaydedildi: {out_path}")
print(f"Toplam satır: {len(df)}, Sütunlar: {df.columns.tolist()}")

📄 Başlangıçtaki satır sayısı: 23626
🔍 Tamamen boş satır sayısı: 0
🔍 URL sütunu boş olan satır sayısı: 0
✅ Temizleme sonrası satır sayısı: 23626
💾 Yeni dosya kaydedildi: C:\Users\elifo\Bitirme_Projesi_Dataset_Olusturma\Phishingdata_all_phishdata_clean_labeled.csv
Toplam satır: 23626, Sütunlar: ['url', 'label']

In [32]:
print("✅ Temiz veri seti satır sayısı:", len(df_check))
df.head()

✅ Temiz veri seti satır sayısı: 23626

                                                 url  label
0  https://www.roblox.tc/games/2753915549/BOMB-Bl...      1
1                           http://www.whatgood.vip/      1
2                             http://www.b45030.com/      1
3                                  http://j209j.xyz/      1
4                        http://www.buysjzh8787.sbs/      1

In [2]:
import os

path = r"C:\Users\elifo\OneDrive\academic\data\phishing_feed_30_days"

if os.path.isdir(path):
    print("✅ Bu bir klasör.")
    print("İçindekiler:")
    for f in os.listdir(path):
        print(" -", f)
elif os.path.isfile(path):
    print("📄 Bu bir dosya.")
    print("Dosya boyutu:", os.path.getsize(path)/1024/1024, "MB")
else:
    print("⚠️ Böyle bir yol yok veya erişilemiyor.")

📄 Bu bir dosya.
Dosya boyutu: 21.81004238128662 MB

In [1]:
import pandas as pd

df = pd.read_csv("success_200.csv")

# main_url bazlı duplicate olanları bul
duplicates = df[df.duplicated("main_url", keep=False)]

# kaç tane duplicate var?
print("Duplicate main_url sayısı:", duplicates["main_url"].nunique())

# sadece tekrar edenleri kaydetmek istersen:
duplicates.to_csv("duplicate_main_urls.csv", index=False)

Duplicate main_url sayısı: 636

In [2]:
dups_list = df["main_url"][df["main_url"].duplicated()].unique()
print(len(dups_list))
print(dups_list)

636
['https://www.google.com/' 'https://www.office.com/' 'https://x.com/'
 'https://www.tiktok.com/explore' 'https://vk.com/'
 'https://outlook.live.com/mail/0/' 'https://www.apple.com/'
 'https://www.mi.com/tr/' 'https://wordpress.com/'
 'https://hotvideo.kwai.com/' 'https://telegram.org/'
 'https://www.baidu.com/' 'https://www.firefox.com/'
 'https://www.amazon.com/' 'https://www.blogger.com/about/?bpli=1'
 'https://www.netflix.com/tr-en/' 'https://www.wix.com/'
 'https://aws.amazon.com/' 'https://www.ozon.ru/'
 'https://www.pinterest.com/' 'https://www.huaweicloud.com/'
 'https://www.salesforce.com/eu/?ir=1&bc=OTH'
 'https://store.steampowered.com/' 'https://liftoff.ai/'
 'https://www.icloud.com/'
 'https://www.primevideo.com/offers/nonprimehomepage/ref=dv_web_force_root'
 'https://www.mozilla.org/' 'https://mailchimp.com/' 'https://thenai.org/'
 'https://www.reddit.com/' 'https://www.kwai.com/'
 'https://www.microsoft.com/tr-tr/microsoft-365/onedrive/online-cloud-storage'
 'https://www.zoom.com'
 'https://registrar.identitydigital.services/Auth/Login'
 'https://www.facebook.com/' 'https://beget.com/'
 'https://www.cloudflare.com/' 'https://wpguardian.com/'
 'https://www.disneyplus.com/' 'https://hdhub4u.gd'
 'https://www.cpanel.net/' 'https://www.threads.com/login/'
 'https://www.hp.com/tr-tr/home.html' 'https://www.avito.ru/'
 'https://www.docker.com/' 'https://www.bitdefender.com/en-bz/'
 'https://jwpconnatix.com/' 'https://www.magnite.com/'
 'https://www.ovhcloud.com/en-ie/' 'https://sweb.ru/'
 'https://www.tbank.ru/' 'https://segment.com/' 'https://kingbokep.tv/'
 'https://www.5movierulz.tienda/' 'https://moviesda14.com/home.html'
 'https://www.intercom.com/' 'https://www.samsung.com/tr/'
 'https://www.linkedin.com' 'https://www.zendesk.com/'
 'https://www.espn.com/' 'https://www.opera.com/' 'https://edna.ru/'
 'https://www.theguardian.com/europe' 'https://www.one.com/'
 'https://www.samsung.com/' 'https://www.lg.com/' 'https://chartbeat.com/'
 'https://www.innovid.com/' 'https://www.aol.com/'
 'https://www.bbc.co.uk/' 'https://www.yahoo.com/'
 'https://www.braze.com/' 'https://unity.com/' 'https://illinois.edu/'
 'https://www.bt.com/' 'https://www.bankofamerica.com/'
 'https://www.jimdo.com/' 'https://blog.google/' 'https://www.notion.com/'
 'https://perion.com/' 'https://www.lg.com/tr/' 'https://ria.ru/'
 'https://www.ubisoft.com/en-gb' 'https://dns.google/'
 'https://www.hbomax.com/' 'https://selectel.ru/'
 'https://marketingplatform.google.com/about/enterprise/'
 'https://www.fortinet.com/' 'https://www.hubspot.com/'
 'https://www.orange.fr/portail' 'https://saby.ru/'
 'https://www.thetimes.com' 'https://bitly.com/' 'https://www.box.com/'
 'https://amp.dev/' 'https://www.themoviedb.org/'
 'https://onenote.cloud.microsoft:443/' 'https://www.dnspod.cn/'
 'https://www.piano.io/' 'https://firebase.google.com/products/hosting/'
 'https://www.dailymotion.com/' 'https://www.nbcuniversal.com/'
 'https://zalo.me/pc' 'https://www.businessinsider.com/'
 'https://www.mintegral.com/en' 'https://imageshack.com/'
 'https://www.atlassian.com/software/statuspage'
 'https://www.dataprivacyframework.gov/' 'https://www.aruba.it/home.aspx'
 'https://www.livechat.com/' 'https://www.minecraft.net/en-us'
 'https://www.razer.com/' 'https://soundcloud.com/'
 'https://sex-studentki.live/index.html' 'https://www.snowflake.com/en/'
 'https://www.nytimes.com/' 'https://www.boutell.co.uk/'
 'https://www.samba.tv/' 'https://account.dyn.com/'
 'https://www.theregister.com/' 'https://blog.npmjs.org/'
 'https://about.gitlab.com/'
 'https://about.readthedocs.com/?ref=app.readthedocs.org'
 'https://vk.company/ru/' 'https://www.trafficjunky.com/'
 'https://keenetic.com.tr/tr' 'https://www.franceinfo.fr/'
 'https://www.gmx.net/' 'https://www.barracuda.com/'
 'https://www.heroku.com/' 'https://www.mcafee.com:443/'
 'https://portal.azure.us/' 'https://outlook.office365.com/mail/'
 'https://www.schneier.com/' 'https://www.wired.com/'
 'https://www.postman.com/' 'https://constellix.digicert.com/'
 'https://www.cib.com.cn/cn/index.html' 'https://www.dropbox.com/'
 'https://www.washington.edu/' 'https://www.oreilly.com/'
 'https://www.nhk.or.jp/' 'https://www.oray.com/'
 'https://www.thomsonreuters.com/en' 'https://www.wyze.com/'
 'https://www.dreamgames.com/' 'https://ok.ru/' 'https://www.ucoz.ru/'
 'https://www.wikipedia.org/' 'https://www.zoho.com/'
 'https://www.microsoft.com/' 'https://www.python.org/'
 'https://www.netlify.com/' 'https://www.verizon.com/'
 'https://www.medallia.com/' 'https://stripe.com'
 'https://app.kit.com/users/login' 'https://www.chinanews.com.cn/'
 'https://go.dev/' 'https://faitid.org/' 'https://kubernetes.io/'
 'https://leavenworth-net.com/' 'https://banco.bradesco/'
 'https://www.oracle.com/cloud/networking/dns/' 'https://liveramp.com/'
 'https://www.telstra.com.au/' 'https://ngrok.com'
 'https://www.xunlei.com/' 'https://www.warnerbros.com/'
 'https://www.joinhoney.com/' 'https://sentby.spotler.com/sendpro'
 'https://www.globalsign.com/en' 'https://grafana.com/'
 'https://www.netskope.com/' 'https://currently.att.yahoo.com/'
 'https://www.goldmansachs.com/' 'https://cursor.com/'
 'https://www.brevo.com/' 'https://www.noip.com/'
 'https://www.epsilon.com/us' 'https://nt.technology/'
 'https://www.deezer.com/tr/' 'https://www.rudderstack.com/'
 'https://www.infomaniak.com/fr' 'https://blog.se.com/'
 'https://www.dell.com/tr-tr' 'https://www.pingdom.com/'
 'https://www.cctv.com/' 'https://wordpress.org/' 'https://www.atom.com/'
 'https://languagetool.org/' 'https://gree.jp/'
 'https://www.logitech.com/tr-tr' 'https://www.mercadolivre.com.br/'
 'https://www.ezoic.com/' 'https://www.crownpeak.com'
 'https://www.free.fr/freebox/' 'https://pusher.com/'
 'https://www.lift.win/' 'https://www.gitbook.com/' 'https://www.wps.cn'
 'https://www.fastly.com/' 'https://sabcencore.co.za/'
 'https://www.olympics.com/en/' 'https://proton.me/mail'
 'https://squareup.com/us/en' 'https://www.digitalocean.com/'
 'https://www.spectrum.net:443/' 'https://www.betway.com'
 'https://www.polybuzz.ai' 'https://www.openweb.com/'
 'https://www.filmyzilla27.com/' 'https://www.eufy.com/'
 'https://streamlabs.com/' 'https://www.moviezwap.haus/'
 'https://www.optimum.net/' 'https://tenjin.com/'
 'https://encrypt.allianz.com/login.xhtml?domain=1319027315'
 'https://www.webnode.com/' 'https://www.gazprombank.ru/'
 'https://www.hubspot.com' 'https://genially.com/'
 'https://www.webroot.com/us/en' 'https://optidigital.com/'
 'https://sift.com/' 'https://www.mxplayer.in/' 'https://www.citi.com/'
 'https://www.arcgis.com/index.html' 'https://kemendikdasmen.go.id/'
 'https://www.qualys.com/' 'https://www.globo.com/'
 'https://www.energy.gov/' 'https://www.kugou.com/'
 'https://www.colorado.gov:443/' 'https://tenor.com/'
 'https://wayground.com/' 'https://vercara.digicert.com/authoritative-dns'
 'https://supabase.com/' 'https://www.foxit.com/'
 'https://bendingspoons.com/' 'https://www.wbs.legal/'
 'https://www.justice.gov/' 'https://www.inquirer.com:443/'
 'https://www.ezviz.com/tr/'
 'https://static-homepage-en.pluto.tv/plutotv-is-not-available'
 'https://www.activecampaign.com/' 'https://www.ibm.com/us-en'
 'https://www.denic.de/' 'https://www.degruyterbrill.com:443/'
 'https://buffer.com/' 'https://www.cj.com/legal/privacy'
 'https://healthy.kaiserpermanente.org/front-door'
 'https://www.cloudmark.com/en' 'https://www.blockchain.com/index.html'
 'https://walletconnect.com/' 'https://goal7.co/'
 'https://moviesmod.plus/' 'https://vegamovies.hot'
 'https://dualeotruyenks.com/' 'https://vu88.net/'
 'https://www.watchmovierulz.onl/' 'https://bollyflix.vet/'
 'https://www.filmyzilla27.net.in/' 'https://www.moviesda.cafe/'
 'https://www.nz131.com/' 'https://www.everythingmomandbaby.com/about/'
 'https://xem.sexnung3x.com/' 'https://tkor071.com/%EC%9B%B9%ED%88%B0'
 'https://shopee.com/' 'https://www.grab.com/sg/'
 'https://www.auswaertiges-amt.de/' 'https://timeweb.com/'
 'https://applovin.com/en' 'https://www.klaviyo.com/'
 'https://www.lmu.de/de/index.html' 'https://avada.com/'
 'https://www.awin.com/' 'https://www.united-domains.de/'
 'https://cloud.tencent.com/'
 'https://accounts.logme.in/login.aspx?nocipsso=1&clusterid=24&returnurl=https%3A%2F%2Fsecure.logmein.com%2Ffederated%2Floginsso.aspx%3Freturnurl%3D%252Fcentral%252Fcentral.aspx%253Ferrorcode%253D6&headerframe=https%3A%2F%2Fsecure.logmein.com%2Ffederated%2Fresources%2Fheaderframe.aspx&productframe=https%3A%2F%2Fsecure.logmein.com%2Fcommon%2Fpages%2Fcls%2Flogin.aspx&lang=en-US&regtype=R&trackingproducttype=2&skin=logmein&useaccesscode=1&customRegUrl=https%3A%2F%2Fsecure.logmein.com%2FPreRegistration%2FProductChoice.aspx'
 'https://sheffield.ac.uk/' 'https://www.adjust.com/' 'https://ghost.org/'
 'https://www.naver.com/' 'https://zingmp3.vn/restrict.html'
 'https://www.nice.com/' 'https://www.ionos.com/'
 'https://www.stnvideo.com/' 'https://corporate.sparteo.com/'
 'https://react.dev/' 'https://imgbb.com/' 'https://ably.com/'
 'https://gameforge.com/' 'http://www.gate.com/'
 'https://www.ice.com/index' 'https://www.iqiyi.com/'
 'https://www.kakaocorp.com/page/' 'https://www.southampton.ac.uk/'
 'https://www.bristol.ac.uk/' 'https://www.kuaishou.com/en'
 'https://tricolor.ru/' 'https://kontur.ru/' 'https://huggingface.co/'
 'https://ring.com/' 'https://www.boomplay.com/'
 'https://mxgpvideogame.com/' 'https://www.seznam.cz/'
 'https://www.okta.com/' 'https://www.tenable.com/'
 'https://www.utorrent.com/' 'https://gnezdo.online/'
 'https://hal.science/' 'https://www.msk-ix.ru/' 'https://www.paddle.com/'
 'https://www.engagelab.com/' 'https://www.wbd.com:443/'
 'https://www.microsoft.com/tr-tr/microsoft-365/previous-versions/skype-for-business-online'
 'https://tr.norton.com/' 'https://www.midea.com.cn/en'
 'https://www.microsoft.com/en-us/windows/' 'https://www.decathlon.com/'
 'https://www.swisscom.ch/de/privatkunden.html' 'https://dstillery.com/'
 'https://www.pair.com/' 'https://www.imperial.ac.uk/'
 'https://home.treasury.gov/' 'https://www.rbc.ru/'
 'https://kpmg.com/xx/en.html'
 'https://www.sap.com/products/hcm.html?src=sfsf'
 'https://www.wunderkind.co/' 'https://decodo.com/'
 'https://www.sydney.edu.au/' 'https://www.telekom.hu/lakossagi'
 'https://www.sonnen.de/' 'https://www.travelsky.com.cn/'
 'https://www.fau.de/' 'https://oriontelekom.rs/' 'https://tapsell.com/'
 'https://www.hts.ru/' 'https://open.spotify.com/'
 'https://www.huffpost.com/' 'https://www.change.org/'
 'https://www.louisiana.gov:443/'
 'https://www.dailymail.co.uk/home/index.html' 'https://crpt.ru/'
 'https://www.merriam-webster.com:443/' 'https://www.bynder.com/en/'
 'http://comingsoon.markmonitor.com/' 'https://wellfound.com/'
 'https://www.uiscom.ru/' 'https://www.freshworks.com/'
 'https://www.telekom.de/start' 'https://988lifeline.org/'
 'https://www.qiniu.com/' 'https://gumgum.com/'
 'https://www.validity.com/everest/returnpath/' 'https://www.linkfire.com'
 'https://www.withings.com/eu/en/' 'https://www.northeastern.edu/'
 'https://www.vpngate.net/en/' 'https://www.knowbe4.com/'
 'https://pushy.me/' 'https://www.amd.com/en.html' 'https://bravenet.com/'
 'https://ren.tv/' 'https://www.ovhcloud.com/en-gb/mail/'
 'https://www.urbandictionary.com/'
 'https://bird.com/developer/email-api?sp=true' 'https://www.mongodb.com/'
 'https://www.khanacademy.org/'
 'https://oci.dyn.com/dynamic-dns-hostname-search/'
 'https://www.skillcup.ru/' 'https://www.rusonyx.ru/' 'https://zt.ru/'
 'https://www.grass.io/' 'https://betterstack.com/' 'https://www.ucs.org/'
 'https://postimages.org/' 'https://tinyurl.com/' 'https://emplifi.io/'
 'https://www.splashtop.com:443/' 'https://www.epic.com/'
 'https://www.wellsfargo.com/' 'https://upsun.com/'
 'https://elfsight.com/' 'https://whiteboard.cloud.microsoft/'
 'https://www.birmingham.ac.uk/' 'https://www.k-state.edu/'
 'https://mapy.com/en/' 'https://www.framer.com/'
 'https://www.humaneworld.org/en' 'https://www.virginmedia.com:443/'
 'https://www.nc.com/' 'https://www.weatherbug.com/'
 'https://www.ccleaner.com/' 'https://www.rhombus.com/'
 'https://customer.io/' 'https://www.itu.int/en/Pages/default.aspx'
 'https://www.volkswagen-group.com/en' 'https://www.airbridge.io/'
 'https://vercel.com' 'https://www.scaleway.com/en/'
 'https://usergate.com/' 'https://webmail.spectrum.net:443/mail/auth'
 'https://viet69.nu/' 'https://www.mayoclinic.org/'
 'https://superwall.com/' 'https://auth.datto.com/login'
 'https://www.thenationalnews.com:443/' 'https://www.kpn.com:443/'
 'https://www.penguinrandomhouse.com/' 'https://futureplc.com/'
 'https://www.bouyguestelecom.fr/' 'https://www.amazonaws.cn/'
 'https://www.mgtv.com/' 'https://www.jpmorganchase.com/'
 'https://www.usps.com/' 'https://www.synchrony.com/'
 'https://www.bnbchain.org/en' 'https://privadovpn.com/'
 'https://www.cafe24.com/' 'https://www.rakuten.tv/'
 'https://moskva.beeline.ru/customers/products/'
 'https://www.gamedeveloper.com/' 'https://www.aepd.es/'
 'https://opamarketplace.com/' 'https://www.shanghai.gov.cn/'
 'https://www.genesys.com/genesys-cloud' 'https://www.chaos.com/'
 'https://www.pew.org/en/' 'https://www.utoronto.ca/'
 'https://www.zara.com/' 'https://www.dialogue.co/en/'
 'https://pixieset.com/' 'https://www.broadcom.com/'
 'https://www.ubereats.com/' 'https://www.people.inc/'
 'https://www.hearstnetworks.com/'
 'https://access.clarivate.com/login?app=wos&alternative=true&shibShireURL=https%3A%2F%2Fwww.webofknowledge.com%2F%3Fauth%3DShibboleth&shibReturnURL=https%3A%2F%2Fwww.webofknowledge.com%2F&roaming=true'
 'https://www.dw.com/' 'https://learn.microsoft.com/en-us/'
 'https://washu.edu/' 'https://www.fing.com:443/'
 'https://www.kantar.com/' 'https://suno.com/home' 'https://asahi-net.jp/'
 'https://screencloud.com/' 'https://infillion.com/'
 'https://pocketcasts.com/' 'https://tekta.ru/' 'https://www.textnow.com/'
 'https://www.gov.uk' 'https://www.larksuite.com/en_sg/?from_site=feishu'
 'https://www.docomo.ne.jp/' 'https://whc.ca/' 'https://www.radmin.com/'
 'https://blend.com/' 'https://www.zhihu.com/signin?next=%2F'
 'https://www.onnetwork.tv/pl/' 'https://xn--d1aqf.xn--p1ai/'
 'https://n8n.io/' 'https://www.nxp.com:443/'
 'https://www.comcasttechnologysolutions.com/' 'https://rumble.com/s/dmca'
 'https://www.files.com/' 'https://www.bloomberg.com/company/'
 'https://admixer.com/' 'https://www.sanofi.com/en' 'https://tilda.cc/'
 'https://lmgtfy.app/'
 'https://www.bitrix24.com.tr/?redirect_from=www.bitrix24.com%2F'
 'https://sudrf.ru/' 'https://www.helpscout.com/' 'https://luma.com/'
 'https://thetrackernetwork.com/Error/NotFound?aspxerrorpath=/index.html'
 'https://badoo.com/' 'https://www.cmtelematics.com/'
 'https://www.ui.com/' 'https://www.verizon.com/business/'
 'https://www.adskeeper.com/' 'https://www.instagram.com/'
 'https://www.harrypotter.com' 'https://www.digitalturbine.com/'
 'https://www.canalplus.com/' 'https://www.jamf.com/'
 'https://www.gambleaware.org:443/' 'https://case.edu/'
 'https://posit.co/' 'https://crowdin.com/'
 'https://www.hatena.ne.jp:443/' 'https://www.photoshelter.com'
 'https://ngs.ru/' 'https://youla.ru/' 'https://www.scopely.com/'
 'https://www.ulisboa.pt/' 'https://inter.co/' 'https://announcekit.app/'
 'https://www.universiteitleiden.nl/' 'https://sputnikglobe.com/'
 'https://www.acast.com/en'
 'https://www.f5.com/products/distributed-cloud-services'
 'https://mobi.com/' 'https://virtualminds.com/'
 'https://vivicomi10.info/' 'https://www.emarketer.com/'
 'https://windsurf.com/' 'https://www.slido.com/'
 'https://www.tiny.cloud/' 'https://xmasti.ac/'
 'https://www.theweathernetwork.com/en' 'https://www.lancaster.ac.uk/'
 'https://transito.mg.gov.br/' 'https://target-video.com/'
 'https://www.citrix.com/' 'https://www.pitneybowes.com/us'
 'https://www.myflorida.gov/' 'https://gba.gob.ar/'
 'https://www.inrae.fr/' 'https://www.mailjet.com/'
 'https://deepmind.google/' 'https://granicus.com/'
 'https://privateemail.com/' 'https://www.omnisend.com/'
 'https://freeddns.dynu.com/' 'https://mts-link.ru/'
 'https://www.reamaze.com/' 'https://elpais.com/' 'https://www.cisa.gov/'
 'https://www.bfm.ru/' 'https://www.aapanel.com/' 'https://www.glia.com/'
 'https://www.louhi.fi/' 'https://www.debian.org/' 'https://itmo.ru/'
 'https://nielseniq.com/global/en/' 'https://www.shopltk.com/'
 'https://www.adaware.com/' 'https://www.groupon.com/'
 'https://www.travis-ci.com/' 'https://www.philips-hue.com/tr-tr'
 'https://unbounce.com/' 'https://embed.ly/' 'https://pp.one/'
 'https://www.videotron.com/' 'https://domrfbank.ru/' 'https://gfi.ai/'
 'https://duo.com/' 'https://www.metanet.ch/de' 'https://www.iij.ad.jp/'
 'https://www.capcut.com/' 'https://www.akbank.com/'
 'https://www.garantibbva.com.tr/' 'https://ibb.istanbul/'
 'https://www.enpara.com/' 'https://www.qnb.com.tr/'
 'https://witanime.day/' 'https://shop.mango.com/tr/tr'
 'https://www.flixbus.com.tr/' 'https://www.softonic.com.tr/'
 'https://bogazici.edu.tr/' 'https://www.lcw.com/'
 'https://www.tarimorman.gov.tr/' 'https://www.lacoste.com.tr/'
 'https://yabancidiziio.com/yabanci-dizi' 'https://www.ktb.gov.tr'
 'https://www.sokmarket.com.tr/' 'https://traidmods.net/'
 'https://www.odatv.com/' 'https://www.hdfilmcehennemi.la/'
 'https://www.arcelik.com.tr/' 'https://turkinform.com.tr/'
 'https://www.digiturk.com.tr/' 'https://www.mebpersonel.net/'
 'https://sflix.ps/' 'https://edesis.com/' 'https://edition.cnn.com/'
 'https://iski.istanbul/' 'https://www.gov.uk/' 'https://egydead.skin/'
 'https://www.kaspersky.com.tr/' 'https://www.agtkurye.com.tr/'
 'https://ikcu.edu.tr/' 'https://bt4gprx.com/' 'https://voe.sx/'
 'https://www.fuzulev.com.tr/' 'https://www.ieu.edu.tr/tr'
 'https://www.alliance4creativity.com/watch-it-legally/'
 'https://www.mokaunited.com/' 'https://www.dhlecommerce.com.tr/'
 'https://www.trt.net.tr/' 'https://sadscans.net/' 'https://finrota.com/'
 'https://www.aselsan.com/tr' 'https://www.stremio.com/'
 'https://www.808fubo11.com/' 'https://yaoiflix.top/'
 'https://www.gedizperakende.com.tr/' 'https://github.com/'
 'https://www.google.com' 'https://selcukflix.net/'
 'https://www.dogakoleji.k12.tr/' 'https://www.bahcelievler.istanbul/'
 'https://www.myheritage.com.tr/'
 'https://eu.shop.battle.net/en-us#optLogin=true' 'https://www.lever.co/'
 'https://www.nhs.uk/' 'https://shop.delonghi.com.tr/'
 'https://www.cosmopolitan.com/' 'https://www.ef.com.tr/'
 'https://filmizledur.com/' 'https://elitanaliz.com/'
 'https://www.albaraka.com.tr/tr' 'https://www.yatasbedding.com.tr/tr'
 'https://www.turkcell.com.tr/' 'https://videomon.biz/'
 'https://www.youtube.com/' 'https://dizikorea1.com/'
 'https://atayatirim.com.tr/' 'https://www.mikro.com.tr/'
 'https://www.loaded.com/' 'https://www.dizibox.live/'
 'https://www.canlitv.top/tr' 'https://www.mynet.com/'
 'https://kickass-anime.ru/' 'https://www.e-bebek.com:443/'
 'https://www.centurygames.com/' 'https://www.faselhds.biz/'
 'https://www.mikrogrup.com/' 'https://abcnews.go.com/'
 'https://www.hdd7.live/' 'https://cavonispizza.com/'
 'https://vymanga.com/' 'https://www.suryapi.com.tr/'
 'https://www.kagithane.istanbul/' 'https://hydrahd.ru/'
 'https://www.emlakkatilim.com.tr/tr']

In [3]:
dup_counts = df["main_url"].value_counts()
dup_counts = dup_counts[dup_counts > 1]
dup_counts.to_csv("duplicate_counts.csv")
dup_counts.head(20)

main_url
https://www.google.com/                                  216
https://outlook.office365.com/mail/                       18
https://registrar.identitydigital.services/Auth/Login     14
https://sentby.spotler.com/sendpro                        11
https://www.salesforce.com/eu/?ir=1&bc=OTH                10
https://www.ucoz.ru/                                       8
https://www.5movierulz.tienda/                             8
https://www.oracle.com/cloud/networking/dns/               8
https://www.ovhcloud.com/en-gb/mail/                       6
https://dns.google/                                        6
https://www.noip.com/                                      6
https://www.cj.com/legal/privacy                           5
https://www.blogger.com/about/?bpli=1                      5
https://www.huaweicloud.com/                               5
https://hdhub4u.gd                                         5
https://www.dnspod.cn/                                     5
https://www.nytimes.com/                                   4
https://www.samsung.com/tr/                                4
https://www.filmyzilla27.com/                              4
https://www.thomsonreuters.com/en                          4
Name: count, dtype: int64

In [4]:
import pandas as pd

df = pd.read_csv("success_200.csv")

# main_url bazlı duplicate olanlardan SADECE İLKİNİ koru
df_unique = df.drop_duplicates(subset="main_url", keep='first')

# temizlenmiş veriyi kaydet
df_unique.to_csv("success_200_unique.csv", index=False)

print("Orijinal satır sayısı:", len(df))
print("Temizlenmiş satır sayısı:", len(df_unique))
print("Silinen duplicate sayısı:", len(df) - len(df_unique))

Orijinal satır sayısı: 25601
Temizlenmiş satır sayısı: 24581
Silinen duplicate sayısı: 1020

In [10]:
import pandas as pd

df = pd.read_csv("./Beningdata/new_url.csv")
print(df["status"].value_counts(dropna=False))
print("\nNaN sayısı:", df[df["main_url"].isna()].shape[0])

status
200.0    14699
NaN       9645
202.0       52
204.0       29
307.0       11
203.0        2
201.0        2
300.0        1
206.0        1
399.0        1
301.0        1
302.0        1
Name: count, dtype: int64

NaN sayısı: 9645