In [1]:
print(3)

3

In [1]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("facebook.com", "https://www.facebook.com/", 200),
    ("windowsupdate.com", "https://www.microsoft.com/", 301),
    ("office.net", "https://www.office.com/", 200),
    ("whatsapp.com", "https://www.whatsapp.com/", 200),
    ("wa.me", "https://wa.me/", 200),
    ("a2z.com", "https://www.amazon.com/", 301),
    ("amazon-adsystem.com", "https://advertising.amazon.com/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)
print("Güncelleme tamamlandı (sadece çalışan URL’ler eklendi).")

Güncelleme tamamlandı (sadece çalışan URL’ler eklendi).

In [2]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("forms.gle", "https://www.google.com/forms/about/", 301),
    ("macromedia.com", "https://www.adobe.com/", 301),
    ("wildberries.ru", "https://www.wildberries.ru/", 200),
    ("ozon.ru", "https://www.ozon.ru/", 200),
    ("chatgpt.com", "https://chat.openai.com/", 301),
    ("sourceforge.net", "https://sourceforge.net/", 200),
    ("sciencedirect.com", "https://www.sciencedirect.com/", 200),
    ("researchgate.net", "https://www.researchgate.net/", 200),
    ("canva.com", "https://www.canva.com/", 200),
    ("openai.com", "https://openai.com/", 200),
    ("youtube-nocookie.com", "https://www.youtube.com/", 301),
    ("playstation.net", "https://www.playstation.com/", 301),
    ("facebook.net", "https://www.facebook.com/", 301),
    ("godaddy.com", "https://www.godaddy.com/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)
print("Güncelleme tamamlandı (sadece çalışan URL'ler eklendi).")

Güncelleme tamamlandı (sadece çalışan URL'ler eklendi).

In [3]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("wildberries.ru", "https://www.wildberries.ru/", 200),
    ("ozon.ru", "https://www.ozon.ru/", 200),
    ("sourceforge.net", "https://sourceforge.net/", 200),
    ("sciencedirect.com", "https://www.sciencedirect.com/", 200),
    ("researchgate.net", "https://www.researchgate.net/", 200),
    ("canva.com", "https://www.canva.com/", 200),
    ("openai.com", "https://openai.com/", 200),
    ("issuu.com", "https://issuu.com/", 200),
    ("etsy.com", "https://www.etsy.com/", 200),
    ("telegraph.co.uk", "https://www.telegraph.co.uk/", 200),
    ("tripadvisor.com", "https://www.tripadvisor.com/", 200),
    ("indeed.com", "https://www.indeed.com/", 200),
    ("unsplash.com", "https://unsplash.com/", 200),
    ("pixabay.com", "https://pixabay.com/", 200),
    ("quora.com", "https://www.quora.com/", 200),
    ("expireddomains.com", "https://www.expireddomains.net/", 200),
    ("arubanetworks.com", "https://www.arubanetworks.com/", 200),
    ("heytapmobile.com", "https://www.heytap.com/", 200),
    ("wb.ru", "https://www.wb.ru/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("Güncelleme tamamlandı (sadece 200 OK siteleri eklendi).")

Güncelleme tamamlandı (sadece 200 OK siteleri eklendi).

In [4]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("behance.net", "https://www.behance.net/", 200),
    ("comcast.com", "https://corporate.comcast.com/", 200),
    ("beian.gov.cn", "https://beian.miit.gov.cn/", 200),
    ("mysql.com", "https://www.mysql.com/", 200),
    ("rzone.de", "https://www.rzone.de/", 200),
    ("rutube.ru", "https://rutube.ru/", 200),
    ("spaceweb.pro", "https://www.spaceweb.com/", 200),
    ("360safe.com", "https://www.360safe.com/", 200),
    ("rakuten.co.jp", "https://www.rakuten.co.jp/", 200),
    ("tandfonline.com", "https://www.tandfonline.com/", 200),
    ("t-mobile.com", "https://www.t-mobile.com/", 200),
    ("intel.com", "https://www.intel.com/", 200),
    ("tencent-cloud.net", "https://www.tencentcloud.com/", 200),
    ("rlcdn.com", "https://www.rubiconproject.com/", 200),
    ("goskope.com", "https://www.netskope.com/", 200),
    ("bdydns.com", "https://www.baidu.com/", 200),
    ("wbbasket.ru", "https://wbbasket.ru/", 200),
    ("adverity.net", "https://www.adverity.com/", 200),
    ("xhamster.com", "https://xhamster.com/", 200),
    ("vtwenty.com", "https://vtwenty.com/", 200),
    ("ozone.ru", "https://www.ozon.ru/", 200),
    ("run.app", "https://run.app/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("Yalnızca 200 OK veren domainler başarıyla eklendi.")

Yalnızca 200 OK veren domainler başarıyla eklendi.

In [5]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("shutterstock.com", "https://www.shutterstock.com/", 200),
    ("cambridge.org", "https://www.cambridge.org/", 200),
    ("pvp.net", "https://pvp.net/", 200),
    ("samsungacr.com", "https://www.samsung.com/", 200),
    ("mysql.com", "https://www.mysql.com/", 200),
    ("comcast.com", "https://corporate.comcast.com/", 200),
    ("intel.com", "https://www.intel.com/", 200),
    ("t-mobile.com", "https://www.t-mobile.com/", 200),
    ("rakuten.co.jp", "https://www.rakuten.co.jp/", 200),
    ("rutube.ru", "https://rutube.ru/", 200),
    ("tandfonline.com", "https://www.tandfonline.com/", 200),
    ("arubanetworks.com", "https://www.arubanetworks.com/", 200),
    ("tencent-cloud.net", "https://www.tencentcloud.com/", 200),
    ("turn.com", "https://www.turn.com/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 Güvenli Global Markaların 200 OK Domainleri Başarıyla Eklendi.")

🌍 %100 Güvenli Global Markaların 200 OK Domainleri Başarıyla Eklendi.

In [7]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("bestbuy.com", "https://www.bestbuy.com/", 200),
    ("markmonitor.com", "https://www.markmonitor.com/", 200),
    ("mdpi.com", "https://www.mdpi.com/", 200),
    ("lgtvcommon.com", "https://www.lg.com/", 200),
    ("allaboutcookies.org", "https://www.allaboutcookies.org/", 200),
    ("allegro.pl", "https://allegro.pl/", 200),
    ("upwork.com", "https://www.upwork.com/", 200),
    ("onlyfans.com", "https://onlyfans.com/", 200),
    ("fidelity.com", "https://www.fidelity.com/", 200),
    ("russianpost.ru", "https://www.pochta.ru/", 200),
    ("usda.gov", "https://www.usda.gov/", 200),
    ("hugedomains.com", "https://www.hugedomains.com/", 200),
    ("pexels.com", "https://www.pexels.com/", 200),
    ("hm.com", "https://www.hm.com/", 200),
    ("kick.com", "https://kick.com/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 Güvenli Global Domainler (200 OK) Başarıyla Eklendi.")

🌍 %100 Güvenli Global Domainler (200 OK) Başarıyla Eklendi.

In [8]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("nintendo.net", "https://www.nintendo.com/", 200),
    ("quizlet.com", "https://quizlet.com/", 200),
    ("nexusmods.com", "https://www.nexusmods.com/", 200),
    ("columbia.edu", "https://www.columbia.edu/", 200),
    ("sofascore.com", "https://www.sofascore.com/", 200),
    ("ouest-france.fr", "https://www.ouest-france.fr/", 200),
    ("olx.com.br", "https://www.olx.com.br/", 200),
    ("skroutz.gr", "https://www.skroutz.gr/", 200),
    ("surfshark.com", "https://surfshark.com/", 200),
    ("businesswire.com", "https://www.businesswire.com/", 200),
    ("bt.co", "https://www.bt.com/", 200),
    ("costco.com", "https://www.costco.com/", 200),
    ("dns-shop.ru", "https://www.dns-shop.ru/", 200),
    ("herokuapp.com", "https://www.heroku.com/", 200),
    ("hltv.org", "https://www.hltv.org/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 Güvenli Global Domainler (200 OK) başarıyla eklendi.")

🌍 %100 Güvenli Global Domainler (200 OK) başarıyla eklendi.

In [9]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("fb.me", "https://www.facebook.com/", 200),
    ("nu.nl", "https://www.nu.nl/", 200),
    ("espncricinfo.com", "https://www.espncricinfo.com/", 200),
    ("hln.be", "https://www.hln.be/", 200),
    ("idealista.com", "https://www.idealista.com/", 200),
    ("makemytrip.com", "https://www.makemytrip.com/", 200),
    ("subito.it", "https://www.subito.it/", 200),
    ("noodlemagazine.com", "https://noodlemagazine.com/", 200),
    ("donmai.us", "https://donmai.us/", 200),
    ("tvn24.pl", "https://tvn24.pl/", 200),
    ("aternos.org", "https://aternos.org/", 200),
    ("perfectdomain.com", "https://www.perfectdomain.com/", 200),
    ("cloudflareclient.com", "https://www.cloudflare.com/", 200),
    ("gst.gov.in", "https://www.gst.gov.in/", 200),
    ("dhl.com", "https://www.dhl.com/", 200),
    ("mediaexpert.pl", "https://www.mediaexpert.pl/", 200),
    ("oecd.org", "https://www.oecd.org/", 200),
    ("leroymerlin.fr", "https://www.leroymerlin.fr/", 200),
    ("idealista.it", "https://www.idealista.it/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 güvenli, global, kurumsal domainler başarıyla eklendi.")

🌍 %100 güvenli, global, kurumsal domainler başarıyla eklendi.

In [10]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("1mg.com", "https://www.1mg.com/", 200),
    ("toyhou.se", "https://toyhou.se/", 200),
    ("novelbin.com", "https://novelbin.com/", 200),
    ("goodreturns.in", "https://www.goodreturns.in/", 200),
    ("arca.live", "https://arca.live/", 200),
    ("cardmarket.com", "https://www.cardmarket.com/", 200),
    ("tesla.com", "https://www.tesla.com/", 200),
    ("autoplius.lt", "https://autoplius.lt/", 200),
    ("skelbiu.lt", "https://www.skelbiu.lt/", 200),
    ("oddspark.com", "https://www.oddspark.com/", 200),
    ("afribaba.com", "https://www.afribaba.com/", 200),
    ("salonboard.com", "https://www.salonboard.com/", 200),
    ("patria.org.ve", "https://www.patria.org.ve/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 Güvenli Global Domainler (200 OK) başarıyla eklendi.")

🌍 %100 Güvenli Global Domainler (200 OK) başarıyla eklendi.

In [11]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("nregastrep.nic.in", "https://nregastrep.nic.in/", 200),
    ("mnregaweb4.nic.in", "https://mnregaweb4.nic.in/", 200),
    ("wowhead.com", "https://www.wowhead.com/", 200),
    ("buydomains.com", "https://www.buydomains.com/", 200),
    ("typepad.com", "https://www.typepad.com/", 200),
    ("sciencemag.org", "https://www.sciencemag.org/", 200),
    ("oneindia.com", "https://www.oneindia.com/", 200),
    ("akamaitechnologies.com", "https://www.akamai.com/", 200),
    ("fb.watch", "https://www.facebook.com/watch", 200),
    ("azure.net", "https://azure.microsoft.com/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 güvenli global domainler başarıyla eklendi.")

🌍 %100 güvenli global domainler başarıyla eklendi.

In [12]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("karnataka.gov.in", "https://karnataka.gov.in/", 200),
    ("bbb.org", "https://www.bbb.org/", 200),
    ("gartner.com", "https://www.gartner.com/", 200),
    ("absher.sa", "https://www.absher.sa/", 200),
    ("pmkisan.gov.in", "https://pmkisan.gov.in/", 200),
    ("thelancet.com", "https://www.thelancet.com/", 200),
    ("jamanetwork.com", "https://jamanetwork.com/", 200),
    ("tixcraft.com", "https://tixcraft.com/", 200),
    ("science.org", "https://www.science.org/", 200),
    ("playtime.com.ph", "https://playtime.com.ph/", 200),
    ("shop.app", "https://shop.app/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 güvenli global domainler başarıyla eklendi.")

🌍 %100 güvenli global domainler başarıyla eklendi.

In [13]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("inc.com", "https://www.inc.com/", 200),
    ("adidas.com", "https://www.adidas.com/", 200),
    ("earthlink.net", "https://www.earthlink.net/", 200),
    ("lego.com", "https://lego.com/", 200),
    ("sfgate.com", "https://www.sfgate.com/", 200),
    ("mgts.ru", "https://mgts.ru/", 200),
    ("nordvpn.com", "https://nordvpn.com/", 200),
    ("proofpoint.us", "https://www.proofpoint.com/", 200),
    ("hpe.com", "https://www.hpe.com/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 güvenli global domainler başarıyla eklendi.")

🌍 %100 güvenli global domainler başarıyla eklendi.

In [14]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("oculus.com", "https://www.oculus.com/", 200),
    ("hhs.gov", "https://www.hhs.gov/", 200),
    ("nipr.mil", "https://nipr.mil/", 200),
    ("java.com", "https://www.java.com/", 200),
    ("opera.software", "https://www.opera.com/", 200),
    ("opera.technology", "https://www.opera.com/", 200),
    ("investing.com", "https://www.investing.com/", 200),
    ("samsungdm.com", "https://www.samsung.com/", 200),
    ("hsforms.com", "https://www.hubspot.com/forms", 200),
    ("usertrust.com", "https://www.usertrust.com/", 200),
    ("shorturl.at", "https://shorturl.at/", 200),
    ("lgsmartad.com", "https://www.lg.com/", 200),
    ("zdassets.com", "https://www.zendesk.com/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 güvenli global domainler başarıyla eklendi.")

🌍 %100 güvenli global domainler başarıyla eklendi.

In [15]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("perplexity.ai", "https://www.perplexity.ai/", 200),
    ("magnit.ru", "https://magnit.ru/", 200),
    ("glassdoor.com", "https://www.glassdoor.com/", 200),
    ("ford.com", "https://www.ford.com/", 200),
    ("meta.com", "https://www.meta.com/", 200),
    ("hyatt.com", "https://www.hyatt.com/", 200),
    ("lww.com", "https://www.lww.com/", 200),
    ("ndtv.com", "https://www.ndtv.com/", 200),
    ("flaticon.com", "https://www.flaticon.com/", 200),
    ("mastercard.com", "https://www.mastercard.com/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)

print("🌍 %100 güvenli global domainler başarıyla eklendi.")

🌍 %100 güvenli global domainler başarıyla eklendi.

In [16]:
import pandas as pd

df = pd.read_csv("domain_scan_results.csv")

updates = [
    ("jimdofree.com", "https://www.jimdo.com/", 200),
    ("congress.gov", "https://www.congress.gov/", 200),
    ("macys.com", "https://www.macys.com/", 200),
    ("drupal.org", "https://www.drupal.org/", 200),
    ("centralnic.net", "https://centralnic.com/", 200),
    ("paramountplus.com", "https://www.paramountplus.com/", 200),
    ("lin.ee", "https://line.me/en/", 200),
]

for domain, url, status in updates:
    df.loc[df["domain"] == domain, "main_url"] = url
    df.loc[df["domain"] == domain, "status"] = status

df.to_csv("domain_scan_results.csv", index=False)
print("🌍 %100 güvenli global domainler başarıyla eklendi.")

🌍 %100 güvenli global domainler başarıyla eklendi.

In [17]:
import pandas as pd

df = pd.read_csv("success_200.csv")
print(df["status"].value_counts(dropna=False))
print("\nNaN sayısı:", df[df["main_url"].isna()].shape[0])

status
200.0    25601
Name: count, dtype: int64

NaN sayısı: 0

In [18]:
import pandas as pd

input_path = "./Beningdata/new_url.csv"
success_output = "./Beningdata/success_200_unique.csv"
final_output = "./Beningdata/first_url.csv"

# new_url.csv'yi oku
df = pd.read_csv(input_path)

# Status kodlarını normalize et (float->int)
df["status"] = pd.to_numeric(df["status"], errors="coerce").astype("Int64")

# Erişilebilir sayılan status kodlar
valid_status = [200, 201, 202, 203, 204, 206]

# Filtrele
df_success = df[df["status"].isin(valid_status)].copy()

print(f"Toplam erişilebilir URL sayısı: {len(df_success)}")

# CSV olarak kaydet
df_success.to_csv(success_output, index=False)
print(f"📁 success_200_unique.csv oluşturuldu: {success_output}")

Toplam erişilebilir URL sayısı: 14785
📁 success_200_unique.csv oluşturuldu: ./Beningdata/success_200_unique.csv

In [19]:
# success_200_unique.csv dosyasını tekrar yükle
df2 = pd.read_csv(success_output)

# Domain + main_url duplicate temizliği
df2 = df2.drop_duplicates(subset=["domain", "main_url"])

# Sadece domain duplicate varsa ilkini tut
df2 = df2.drop_duplicates(subset=["domain"])

# Redirect sonrası URL duplicate varsa da temizle
df2 = df2.drop_duplicates(subset=["main_url"])

# Final olarak kaydet
df2.to_csv(final_output, index=False)

print(f"📁 first_url.csv oluşturuldu: {final_output}")
print(f"Kalan final URL sayısı: {len(df2)}")

📁 first_url.csv oluşturuldu: ./Beningdata/first_url.csv
Kalan final URL sayısı: 14556

In [22]:
import pandas as pd

# Doğru dosya yolları
new_url_path = "./Beningdata/new_url.csv"               # 🔴 BURASI ÖNEMLİ
success_path = "./Beningdata/success_200_unique.csv"
output_path = "./Beningdata/firstt_url.csv"

# CSV'leri yükle
df_new = pd.read_csv(new_url_path)
df_succ = pd.read_csv(success_path)

# Birleştir
df_merged = pd.concat([df_new, df_succ], ignore_index=True)

# Domain / URL'leri normalize et (opsiyonel ama faydalı)
df_merged["domain"] = df_merged["domain"].astype(str).str.strip().str.lower()
if "main_url" in df_merged.columns:
    df_merged["main_url"] = df_merged["main_url"].astype(str).str.strip()

# Sadece gerçekten URL'i olanları tut (NaN veya boşları atmak istiyorsan)
df_merged = df_merged.dropna(subset=["main_url"])
df_merged = df_merged[df_merged["main_url"].str.strip() != ""]

# SADECE domain + main_url bazlı duplicate temizliği
df_merged = df_merged.drop_duplicates(subset=["domain", "main_url"])

# Kaydet
df_merged.to_csv(output_path, index=False)

print("Birleştirme ve duplicate temizliği tamamlandı!")
print(f"Toplam final satır sayısı: {len(df_merged)}")
print(f"Kayıt edilen dosya: {output_path}")

Birleştirme ve duplicate temizliği tamamlandı!
Toplam final satır sayısı: 24445
Kayıt edilen dosya: ./Beningdata/firstt_url.csv

In [23]:
import pandas as pd

# Dosya yolları
success_path = "./success_200_unique.csv"
new_url_path = "./new_url.csv"
output_path = "./final_first_step_url.csv"

# CSV'leri yükle
df_success = pd.read_csv(success_path)
df_new = pd.read_csv(new_url_path)

# 🔹 Sadece domain, main_url, status kolonlarını al
df_success = df_success[["domain", "main_url", "status"]]
df_new = df_new[["domain", "main_url", "status"]]

# 🔹 Birleştir (append + index reset)
df_merged = pd.concat([df_success, df_new], ignore_index=True)

# 🔹 Duplicate temizliği (domain + main_url bazlı)
df_merged = df_merged.drop_duplicates(subset=["domain", "main_url"])

# 🔹 Kaydet
df_merged.to_csv(output_path, index=False)

print("Birleştirme ve duplicate temizliği tamamlandı!")
print(f"Toplam final kayıt sayısı: {len(df_merged)}")
print(f"Oluşturulan dosya: {output_path}")

Birleştirme ve duplicate temizliği tamamlandı!
Toplam final kayıt sayısı: 49026
Oluşturulan dosya: ./final_first_step_url.csv

In [24]:
import pandas as pd

csv_path = "./final_first_step_url.csv"

# Dosyayı yükle
df = pd.read_csv(csv_path)

# main_url NaN olan verileri sil
df = df.dropna(subset=["main_url"])

# Tekrar aynı dosyaya kaydet
df.to_csv(csv_path, index=False)

print("main_url'i NaN olan satırlar silindi.")
print(f"Kalan satır sayısı: {len(df)}")

main_url'i NaN olan satırlar silindi.
Kalan satır sayısı: 39381

In [25]:
import pandas as pd

csv_path = "./final_first_step_url.csv"

# Dosyayı yükle
df = pd.read_csv(csv_path)

# Duplicate olan main_url kayıtlarını bul (kendisi hariç)
duplicate_count = df.duplicated(subset=["main_url"]).sum()

print(f"main_url bazlı duplicate kayıt sayısı: {duplicate_count}")

# Duplicate olanları sil (ilk satırı bırak)
df = df.drop_duplicates(subset=["main_url"], keep="first")

# Aynı dosyaya geri yaz
df.to_csv(csv_path, index=False)

print("Duplicate main_url kayıtları temizlendi.")
print(f"Yeni toplam satır sayısı: {len(df)}")

main_url bazlı duplicate kayıt sayısı: 676
Duplicate main_url kayıtları temizlendi.
Yeni toplam satır sayısı: 38705

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
import uuid

# Giriş ve çıkış
input_path = "./final_first_step_url.csv"
output_path = "./real_paths_test.csv"

df = pd.read_csv(input_path).head(100)  # Pilot: ilk 100 URL

results = []

def extract_links(base_url):
    """
    Gerçek sayfadan link çeken fonksiyon
    """
    try:
        r = requests.get(base_url, timeout=10)
        if r.status_code != 200:
            return []

        soup = BeautifulSoup(r.text, "html.parser")
        domain = urlparse(base_url).netloc

        found_paths = []
        for tag in soup.find_all("a", href=True):
            href = tag.get("href")

            # Absolute URL’ye çevir
            full_url = urljoin(base_url, href)

            # Aynı domain mi?
            if urlparse(full_url).netloc == domain:
                path = urlparse(full_url).path
                if path and path not in ["", "/", None]:
                    found_paths.append(path)

        # Duplicate temizle
        found_paths = list(set(found_paths))
        return found_paths

    except Exception:
        return []

for idx, row in df.iterrows():
    base_url = row["main_url"]
    domain = row["domain"]

    print(f"[+] Tarama: {base_url}")

    # Path ID üret
    path_id = str(uuid.uuid4())

    paths = extract_links(base_url)

    for p in paths:
        full_url = base_url.rstrip("/") + p
        results.append({
            "domain": domain,
            "main_url": base_url,
            "real_path": p,
            "full_real_url": full_url,
            "path_id": path_id,
            "status": row["status"]
        })

# CSV kaydet
pd.DataFrame(results).to_csv(output_path, index=False)

print("Gerçek alt path taraması (pilot 100 URL) tamamlandı.")
print(f"Toplam bulunan gerçek path sayısı: {len(results)}")
print(f"Veriler kaydedildi: {output_path}")

[+] Tarama: https://www.google.com/
[+] Tarama: https://account.mail.ru/login?autologin_exp=v22&autologin_project=home&page=https://mail.ru/?autologin%3D1763121884&errorCode=11300&errorText=invalid+user&state=e21ba3c2b70d422bbddc7b04502733f6
[+] Tarama: https://www.microsoft.com/
[+] Tarama: https://www.facebook.com/
[+] Tarama: https://www.cloudflare.com/
[+] Tarama: https://aws.amazon.com/
[+] Tarama: https://sso.passport.yandex.ru/push?uuid=6f496770-2c56-4df2-8ff2-03d4224c3aaa&retpath=https%3A%2F%2Fdzen.ru%2F%3Fis_autologin_ya%3Dtrue
[+] Tarama: https://www.youtube.com/
[+] Tarama: https://www.apple.com/
[+] Tarama: https://www.instagram.com/
[+] Tarama: https://www.office.com/
[+] Tarama: https://x.com/
[+] Tarama: https://outlook.live.com/mail/0/
[+] Tarama: https://www.linkedin.com/
[+] Tarama: https://www.amazon.com/
[+] Tarama: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=4765445b-32c6-49b0-83e6-1d93765276ca&redirect_uri=https%3A%2F%2Fwww.microsoft365.com%2Flandingv2&response_type=code%20id_token&scope=openid%20profile%20https%3A%2F%2Fwww.office.com%2Fv2%2FOfficeHome.All&response_mode=form_post&nonce=638987186940719170.MDZmNzNmNjYtYzVhYi00ZDZmLWE1NTYtYTM1YTk0NWUyMjRhN2Y4ODQwMDgtMGI1Ni00ZTQ0LTg0ZmQtNTkwZDE2ZWVmMzdj&ui_locales=en-US&mkt=en-US&client-request-id=14c80833-3dcc-4dd5-a847-cf6a6b0fa3df&state=uVh9XYEVStBstBFvKGdoJI6pArvF6CU303GDBbS7RzA4-iwPYFBx4bTMr-2jyIMKH6UPH9OOsK6z0v3C8_zM7BfoK1HuXcKjoX58167fW6jeOw78g_WLzilri9qUxsTtxdcuQzo3suKCBGmbqP8LbK9Kz-REj0QPrD621GeIllJM2uw0e1Vdl2OJe067dyYmsHe_FDIKtY06UcTroxKTA2PkE8QtRxTeNhC9Q2X42CSYE7AFkNJ_NDxP9vSUULHfnsGwK0xrU9b0oZI2JaJ5aGoAYmp3R2D15trkXiOxCnjvdHzIseo9BYQ38tE4Tf-9ZmthFoRnWrp6g9X16z4-LA&x-client-SKU=ID_NET8_0&x-client-ver=8.5.0.0
[+] Tarama: https://workers.cloudflare.com
[+] Tarama: https://marketingplatform.google.com/about/enterprise/
[+] Tarama: https://www.wikipedia.org/
[+] Tarama: https://portal.azure.com/
[+] Tarama: https://www.bing.com:443/?toWww=1&redig=B0B430995E4C4A628DC268027F4896A0
[+] Tarama: https://github.com/
[+] Tarama: https://www.fastly.com/
[+] Tarama: https://www.netflix.com/tr-en/
[+] Tarama: https://wordpress.org/
[+] Tarama: https://www.digicert.com/
[+] Tarama: https://www.youtube.com/?feature=youtu.be
[+] Tarama: https://www.icloud.com/
[+] Tarama: https://www.pinterest.com/
[+] Tarama: https://app.trafficmanager.net/
[+] Tarama: https://www.yahoo.com/
[+] Tarama: https://www.microsoft.com/tr-tr/microsoft-365/sharepoint/collaboration?ms.officeurl=sharepoint
[+] Tarama: https://nic.ru/
[+] Tarama: https://dotnet.microsoft.com/en-us/
[+] Tarama: https://www.ntp.org/
[+] Tarama: https://www.whatsapp.com/
[+] Tarama: https://teams.live.com/free?source=skype
[+] Tarama: https://www.msn.com/tr-tr
[+] Tarama: https://portal.adobe.com/
[+] Tarama: https://roblox.com/
[+] Tarama: https://www.tiktok.com/explore
[+] Tarama: https://vimeo.com/
[+] Tarama: https://open.spotify.com/
[+] Tarama: https://www.gandi.net/en
[+] Tarama: https://bitly.com/
[+] Tarama: https://www.qq.com/
[+] Tarama: https://www.zoom.com
[+] Tarama: https://www.microsoft.com/tr-tr/microsoft-365?ms.url=office365com
[+] Tarama: https://www.opera.com/
[+] Tarama: https://ya.ru/?nr=1&redirect_ts=1763121902.00000
[+] Tarama: https://wordpress.com/
[+] Tarama: https://www.samsung.com/tr/
[+] Tarama: https://marketingplatform.google.com/about/analytics/
[+] Tarama: https://www.baidu.com/
[+] Tarama: https://one.one.one.one/dns/
[+] Tarama: https://wa.me/
[+] Tarama: https://domains.google/
[+] Tarama: https://nginx.org/
[+] Tarama: https://www.mozilla.org/
[+] Tarama: https://www.microsoft.com/en-us/windows/
[+] Tarama: https://www.reddit.com/
[+] Tarama: https://www.f5.com/go/product/welcome-to-nginx
[+] Tarama: https://ui.com/
[+] Tarama: https://unity.com/
[+] Tarama: https://www.blogger.com/about/?bpli=1
[+] Tarama: https://telegram.org/
[+] Tarama: https://vk.com/
[+] Tarama: https://advertising.amazon.com/
[+] Tarama: https://sentry.io/welcome/
[+] Tarama: https://european-union.europa.eu/select-language?destination=/node/1
[+] Tarama: https://www.criteo.com/
[+] Tarama: https://www.snapchat.com:443/
[+] Tarama: https://www.intuit.com/
[+] Tarama: https://dns.google/
[+] Tarama: https://apache.org/
[+] Tarama: https://pages.github.com/
[+] Tarama: https://www.adriver.ru/
[+] Tarama: https://www.one.com/
[+] Tarama: https://gravatar.com/
[+] Tarama: https://www.paypal.com/tr/home
[+] Tarama: https://www.dropbox.com/
[+] Tarama: https://www.mi.com/tr/
[+] Tarama: https://www.telekom.de/start
[+] Tarama: https://sso.passport.yandex.ru/push?uuid=41466bd8-85d9-41eb-90e2-767888574ba9&retpath=https%3A%2F%2Fdzen.ru%2F%3Fyredirect%3Dtrue%26is_autologin_ya%3Dtrue
[+] Tarama: https://www.tumblr.com/
[+] Tarama: https://www.nist.gov/
[+] Tarama: https://www.miit.gov.cn/
[+] Tarama: https://discord.gg/index.html

In [1]:
import pandas as pd

# CSV dosyasını yükle
df = pd.read_csv("real_paths_master.csv")

# Kaç farklı url_id var?
unique_count = df["url_id"].nunique()

print("Kullanılan farklı url_id sayısı:", unique_count)

Kullanılan farklı url_id sayısı: 142

In [1]:
pip install selenium pandas beautifulsoup4

Collecting selenium
  Downloading selenium-4.38.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: pandas in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (2.3.3)
Requirement already satisfied: beautifulsoup4 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (4.14.2)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (2.5.0)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.32.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Using cached trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: certifi>=2025.10.5 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from selenium) (2025.10.5)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: exceptiongroup in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.1-py3-none-any.whl.metadata (5.2 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.5.0->selenium)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.22.4 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: pycparser in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: six>=1.5 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\elifo\anacond3\envs\lungai\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.38.0-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.7 MB 4.5 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.7 MB 5.2 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.7 MB 5.3 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.7 MB 5.5 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.7 MB 5.6 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.7 MB 5.0 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.7 MB 4.9 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.7 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 4.8 MB/s  0:00:02
Downloading trio-0.32.0-py3-none-any.whl (512 kB)
Using cached trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.1-py3-none-any.whl (24 kB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, wsproto, pysocks, outcome, trio, trio-websocket, selenium

   ----- ---------------------------------- 1/7 [wsproto]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------------- 7/7 [selenium]

Successfully installed outcome-1.3.0.post0 pysocks-1.7.1 selenium-4.38.0 sortedcontainers-2.4.0 trio-0.32.0 trio-websocket-0.12.2 wsproto-1.3.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import time
import uuid
import concurrent.futures
from urllib.parse import urlparse, urljoin

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

# ================== KONFİG ==================

input_path = "./final_first_step_url.csv"   # CSV'ni buraya koy
output_path = "./real_paths_depth2_selenium.csv"

MAX_FIRST_LEVEL_LINKS = 10      # main_url'den toplanacak max link
MAX_SECOND_LEVEL_LINKS = 10     # her first-level URL'den toplanacak max link
MAX_WORKERS = 3                 # aynı anda kaç domain taransın (Selenium olduğu için çok yüksek olmasın)

REQUEST_SLEEP = (0.5, 1.2)      # her istek sonrası min-max bekleme aralığı (saniye)
TEST_LIMIT = 100                # ilk deneme için: kaç main_url taransın? Tüm dataset için None yapabilirsin.

# Statik dosya uzantıları (indirme linkleri vs. istemiyoruz)
STATIC_EXTENSIONS = (
    ".jpg", ".jpeg", ".png", ".gif", ".svg",
    ".webp", ".ico",
    ".pdf", ".zip", ".rar", ".7z", ".tar", ".gz",
    ".mp4", ".mp3", ".avi", ".mov", ".mkv",
    ".exe", ".msi", ".dmg"
)


# ================== YARDIMCI FONKSİYONLAR ==================

def create_driver():
    """
    Headless Chrome driver oluşturur.
    """
    chrome_options = Options()
    chrome_options.add_argument("--headless=new")   # eski Chrome için "--headless" da olur
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )

    driver = webdriver.Chrome(options=chrome_options)
    driver.set_page_load_timeout(20)
    return driver


def random_sleep():
    """Her istek sonrası küçük bir bekleme (ban riskini azaltmak için)."""
    import random
    time.sleep(random.uniform(*REQUEST_SLEEP))


def clean_and_filter_link(base_url, href, allowed_domain):
    """
    href'i absolute URL'ye çevirir, filtreler ve (full_url, path) döner.
    İstemediğimiz şeyleri eliyoruz:
      - mailto:, javascript:, tel:
      - dış domain
      - boş path veya '/'
      - statik dosyalar (jpg, pdf vs)
    """
    if not href:
        return None

    href = href.strip()

    # İstemediğimiz protokoller
    if href.startswith(("mailto:", "javascript:", "tel:", "#")):
        return None

    full = urljoin(base_url, href)
    parsed = urlparse(full)

    # Sadece http/https
    if parsed.scheme not in ("http", "https"):
        return None

    # Aynı domain değilse alma
    if parsed.netloc != allowed_domain:
        return None

    path = parsed.path or "/"

    # Ana sayfa path'i istemiyorsak:
    if path in ("", "/"):
        return None

    # Statik dosyaları ele
    for ext in STATIC_EXTENSIONS:
        if path.lower().endswith(ext):
            return None

    return full, path


def extract_links_js(driver, base_url, domain, max_links):
    """
    Selenium ile JS-render edilmiş sayfadan link toplar.
    Sadece aynı domain ve filtreleri geçen linkleri döner.
    max_links kadar benzersiz path döndürür.
    """
    links = []
    seen_paths = set()

    try:
        driver.get(base_url)
        # JS'in çalışması için biraz bekle
        time.sleep(1.5)

        anchors = driver.find_elements(By.TAG_NAME, "a")

        for a in anchors:
            href = a.get_attribute("href")
            # Bazı sitelerde data-href vs. kullanılabilir, istersen buraya ekleyebiliriz.
            if not href:
                continue

            cleaned = clean_and_filter_link(base_url, href, domain)
            if not cleaned:
                continue

            full_url, path = cleaned

            if path in seen_paths:
                continue

            seen_paths.add(path)
            links.append((full_url, path))

            if len(links) >= max_links:
                break

    except Exception as e:
        # Hata olursa o sayfayı pas geç
        # print(f"[!] extract_links_js hata: {base_url} -> {e}")
        return []

    random_sleep()
    return links


# ================== ASIL CRAWLER (Depth=2) ==================

def crawl_main_url(row):
    """
    Tek bir main_url satırı için:
      - Level 1: main_url'den MAX_FIRST_LEVEL_LINKS kadar link
      - Level 2: her Level 1 linkinden MAX_SECOND_LEVEL_LINKS kadar link
    Sonuçta satır listesi (dict) döner.
    Her thread kendi Selenium driver'ını kullanır.
    """
    domain = row["domain"]
    main_url = row["main_url"]
    status = row.get("status", None)

    # Domain netloc doğrulama için
    parsed_main = urlparse(main_url)
    base_domain = parsed_main.netloc
    if not base_domain:
        # Geçersiz URL
        return []

    path_tree_id = str(uuid.uuid4())
    results = []
    visited = set()  # aynı current_url'e tekrar gitmemek için

    driver = None
    try:
        driver = create_driver()

        # ---- LEVEL 1 ----
        first_level_links = extract_links_js(
            driver=driver,
            base_url=main_url,
            domain=base_domain,
            max_links=MAX_FIRST_LEVEL_LINKS
        )

        for full_url, path in first_level_links:
            if full_url in visited:
                continue
            visited.add(full_url)

            results.append({
                "domain": domain,
                "main_url": main_url,
                "parent_url": main_url,
                "current_url": full_url,
                "real_path": path,
                "depth": 1,
                "status": status,
                "path_tree_id": path_tree_id
            })

        # ---- LEVEL 2 ----
        for full_url_level1, path_level1 in first_level_links:
            second_level_links = extract_links_js(
                driver=driver,
                base_url=full_url_level1,
                domain=base_domain,
                max_links=MAX_SECOND_LEVEL_LINKS
            )

            for full_url2, path2 in second_level_links:
                if full_url2 in visited:
                    continue
                visited.add(full_url2)

                results.append({
                    "domain": domain,
                    "main_url": main_url,
                    "parent_url": full_url_level1,
                    "current_url": full_url2,
                    "real_path": path2,
                    "depth": 2,
                    "status": status,
                    "path_tree_id": path_tree_id
                })

    except Exception as e:
        # print(f"[!] crawl_main_url hata: {main_url} -> {e}")
        pass
    finally:
        if driver is not None:
            try:
                driver.quit()
            except Exception:
                pass

    return results


# ================== ANA AKIŞ ==================

# CSV'yi yükle
df = pd.read_csv(input_path)

# İlk test için subset al; her şey yolundaysa bu satırı kaldırabilirsin
if TEST_LIMIT is not None:
    df = df.head(TEST_LIMIT)

print(f"Toplam main_url sayısı (bu koşuda): {len(df)}")

all_results = []

with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    future_to_idx = {
        executor.submit(crawl_main_url, row): idx
        for idx, row in df.iterrows()
    }

    for future in concurrent.futures.as_completed(future_to_idx):
        idx = future_to_idx[future]
        try:
            res = future.result()
            if res:
                all_results.extend(res)
        except Exception as e:
            print(f"[!] Thread hatası, satır {idx}: {e}")

# Sonuçları CSV'ye yaz
if all_results:
    out_df = pd.DataFrame(all_results)
    out_df.to_csv(output_path, index=False)
    print(f"Toplam bulunan URL sayısı: {len(out_df)}")
    print(f"Kaydedilen dosya: {output_path}")
else:
    print("Hiç URL bulunamadı veya tüm istekler hata verdi.")

Toplam main_url sayısı (bu koşuda): 100
Toplam bulunan URL sayısı: 1769
Kaydedilen dosya: ./real_paths_depth2_selenium.csv

In [3]:
import pandas as pd

# CSV dosyasını yükle
df = pd.read_csv("real_paths_depth2_selenium.csv")

# Kaç farklı domain var?
unique_domains = df["domain"].nunique()

print("Toplam farklı domain sayısı:", unique_domains)

Toplam farklı domain sayısı: 74

In [4]:
avg_urls = df.groupby("domain")["current_url"].count().mean()
print("Domain başına ortalama URL:", avg_urls)

Domain başına ortalama URL: 23.905405405405407

In [8]:
import pandas as pd

# CSV dosyasını yükle
df = pd.read_csv("real_paths_depth2_selenium.csv")

# İncelemek istediğin domain
target_domain = "microsoft.com"   # ← buraya istediğin domaini yaz

# O domainin pathlerini al
domain_paths = df[df["domain"] == target_domain]["current_url"].unique()

print(f"{target_domain} için bulunan path sayısı: {len(domain_paths)}")
for p in domain_paths:
    print(p)

microsoft.com için bulunan path sayısı: 76
https://www.microsoft.com/tr-tr/microsoft-365
https://www.microsoft.com/tr-tr/microsoft-teams/group-chat-software
https://www.microsoft.com/tr-tr/windows/
https://www.microsoft.com/tr-tr/ai
https://www.microsoft.com/tr-tr/microsoft-365/onedrive/online-cloud-storage
https://www.microsoft.com/tr-tr/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook
https://www.microsoft.com/tr-tr/microsoft-365/onenote/digital-note-taking-app
https://www.microsoft.com/tr-tr/accessories
https://www.microsoft.com/tr-tr/microsoft-cloud
https://www.microsoft.com/tr-tr/security
https://www.microsoft.com/tr-tr/microsoft-365/buy/compare-all-microsoft-365-products
https://www.microsoft.com/tr-tr/microsoft-365/p/microsoft-365-family/cfq7ttc0k5dm
https://www.microsoft.com/tr-tr/microsoft-365/p/microsoft-365-premium/cfq7ttc11z3q
https://www.microsoft.com/tr-tr/education/students
https://www.microsoft.com/tr-tr/microsoft-365/explore-microsoft-365-for-home
https://www.microsoft.com/tr-tr/microsoft-365/business/microsoft-365-plans-and-pricing
https://www.microsoft.com/tr-tr/microsoft-365/business
https://www.microsoft.com/tr-tr/education/products/microsoft-365
https://www.microsoft.com/tr-tr/microsoft-365/enterprise/microsoft-365-plans-and-pricing
https://www.microsoft.com/tr-tr/microsoft-teams/teams-free
https://www.microsoft.com/tr-tr/microsoft-teams/small-medium-business
https://www.microsoft.com/tr-tr/microsoft-teams/enterprise
https://www.microsoft.com/tr-tr/microsoft-teams/education
https://www.microsoft.com/tr-tr/microsoft-teams/teams-products
https://www.microsoft.com/tr-tr/microsoft-teams/premium
https://www.microsoft.com/tr-tr/microsoft-teams/microsoft-teams-phone
https://www.microsoft.com/tr-tr/microsoft-teams/microsoft-teams-rooms
https://www.microsoft.com/tr-tr/microsoft-teams/across-devices
https://www.microsoft.com/tr-tr/windows
https://www.microsoft.com/tr-tr/windows/windows-11
https://www.microsoft.com/tr-tr/windows/compare-windows-11-home-vs-pro-versions
https://www.microsoft.com/tr-tr/windows/comprehensive-security
https://www.microsoft.com/tr-tr/windows/ai-features
https://www.microsoft.com/tr-tr/windows/photo-movie-editor
https://www.microsoft.com/tr-tr/windows/paint
https://www.microsoft.com/tr-tr/windows/digital-pen-touch-voice-features
https://www.microsoft.com/tr-tr/windows/apps-for-windows
https://www.microsoft.com/tr-tr/windows/windows-11-pc-gaming
https://www.microsoft.com/tr-tr/microsoft-copilot/for-individuals
https://www.microsoft.com/tr-tr/microsoft-copilot/for-individuals/get-copilot
https://www.microsoft.com/tr-tr/microsoft-365-copilot
https://www.microsoft.com/tr-tr/microsoft-365-copilot/download-copilot-app
https://www.microsoft.com/tr-tr/microsoft-copilot/organizations
https://www.microsoft.com/tr-tr/microsoft-365-copilot/microsoft-copilot-studio
https://www.microsoft.com/tr-tr/windows/copilot-plus-pcs
https://www.microsoft.com/tr-tr/ai/ai-business-value-and-benefits
https://www.microsoft.com/tr-tr/ai/use-case
https://www.microsoft.com/tr-tr/microsoft-365/onedrive/onedrive-for-business
https://www.microsoft.com/tr-tr/microsoft-365/onedrive/compare-onedrive-plans?activetab=tab:primaryr1
https://www.microsoft.com/tr-tr/microsoft-365/onedrive/document-scanning
https://www.microsoft.com/tr-tr/microsoft-365/onedrive/onedrive-photos
https://www.microsoft.com/tr-tr/microsoft-365/onedrive/free-online-cloud-storage/
https://www.microsoft.com/tr-tr/microsoft-365/onedrive/personal-vault
https://www.microsoft.com/tr-tr/microsoft-365/onedrive/pc-cloud-backup
https://www.microsoft.com/tr-tr/microsoft-365/onedrive-for-business/apps-that-work-with-onedrive
https://www.microsoft.com/tr-tr/microsoft-365/outlook/outlook-for-windows
https://www.microsoft.com/tr-tr/microsoft-365/outlook/outlook-for-mac
https://www.microsoft.com/tr-tr/microsoft-365/outlook/web-email-login-for-outlook
https://www.microsoft.com/tr-tr/microsoft-365/outlook-mobile-for-android-and-ios
https://www.microsoft.com/tr-tr/microsoft-365/outlook/outlook-for-business
https://www.microsoft.com/tr-tr/microsoft-365/outlook/outlook-email-plan
https://www.microsoft.com/tr-tr/microsoft-365/outlook/outlook-business-email-plans
https://www.microsoft.com/tr-tr/microsoft-365/outlook/ai-email-assistant
https://www.microsoft.com/microsoft-365/buy/compare-all-microsoft-365-products?ocid=cmm1qycerth
https://www.microsoft.com/microsoft-365?ocid=cmmttvzgpuy
https://www.microsoft.com/microsoft-365/microsoft-office?ocid=cmml7tr0rib
https://www.microsoft.com/reportascam/
https://www.microsoft.com/tr-tr/security/why-microsoft-security
https://www.microsoft.com/tr-tr/security/business/solutions/generative-ai-cybersecurity
https://www.microsoft.com/tr-tr/security/business/solutions/cloud-security
https://www.microsoft.com/tr-tr/security/business/solutions/data-security-governance
https://www.microsoft.com/tr-tr/security/business/solutions/identity-access
https://www.microsoft.com/tr-tr/security/business/solutions/privacy-risk-management
https://www.microsoft.com/tr-tr/security/business/solutions/security-for-ai
https://www.microsoft.com/tr-tr/security/business/solutions/ai-powered-unified-secops-platform
https://www.microsoft.com/tr-tr/security/business/zero-trust

In [9]:
import pandas as pd
import time
import uuid
import concurrent.futures
import os
from urllib.parse import urlparse, urljoin
from datetime import datetime

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

# ================== KONFİG ==================

input_path = "./final_first_step_url.csv"     # Girdi CSV
output_path = "./real_paths_depth2_vs2_selenium.csv"      # URL’lerin kaydedileceği dosya
no_url_output_path = "./no_urls_depth2_selenium.csv"  # Hiç URL üretemeyen main_url’ler

MAX_FIRST_LEVEL_LINKS = 5       # Depth 1: main_url'den toplanacak max link sayısı
MAX_SECOND_LEVEL_LINKS = 10     # Depth 2: her first-level URL'den toplanacak max link sayısı

MAX_WORKERS = 3                 # Aynı anda kaç domain taransın (Selenium, çok abartma)
REQUEST_SLEEP = (0.5, 1.2)      # Her istek sonrası min-max bekleme (saniye)

CHECKPOINT_EVERY = 20           # Her 20 main_url'de bir ara kayıt
TEST_LIMIT = 100                # İlk 100 main_url ile test

# Statik dosya uzantıları (indirme linkleri vs. istemiyoruz)
STATIC_EXTENSIONS = (
    ".jpg", ".jpeg", ".png", ".gif", ".svg",
    ".webp", ".ico",
    ".pdf", ".zip", ".rar", ".7z", ".tar", ".gz",
    ".mp4", ".mp3", ".avi", ".mov", ".mkv",
    ".exe", ".msi", ".dmg"
)


# ================== YARDIMCI FONKSİYONLAR ==================

def create_driver():
    """
    Headless Chrome driver oluşturur.
    """
    chrome_options = Options()
    chrome_options.add_argument("--headless=new")   # Gerekirse "--headless" yap
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )

    driver = webdriver.Chrome(options=chrome_options)
    driver.set_page_load_timeout(20)
    return driver


def random_sleep():
    """Her istek sonrası küçük bir bekleme (ban riskini azaltmak için)."""
    import random
    time.sleep(random.uniform(*REQUEST_SLEEP))


def clean_and_filter_link(base_url, href, allowed_domain):
    """
    href'i absolute URL'ye çevirir, filtreler ve (full_url, path) döner.
    İstemediğimiz şeyleri eliyoruz:
      - mailto:, javascript:, tel:, #
      - dış domain
      - boş path veya '/'
      - statik dosyalar (jpg, pdf vs)
    """
    if not href:
        return None

    href = href.strip()

    # İstemediğimiz protokoller
    if href.startswith(("mailto:", "javascript:", "tel:", "#")):
        return None

    full = urljoin(base_url, href)
    parsed = urlparse(full)

    # Sadece http/https
    if parsed.scheme not in ("http", "https"):
        return None

    # Aynı domain değilse alma
    if parsed.netloc != allowed_domain:
        return None

    path = parsed.path or "/"

    # Ana sayfa path'i istemiyorsak:
    if path in ("", "/"):
        return None

    # Statik dosyaları ele
    for ext in STATIC_EXTENSIONS:
        if path.lower().endswith(ext):
            return None

    return full, path


def extract_links_js(driver, base_url, domain, max_links):
    """
    Selenium ile JS-render edilmiş sayfadan link toplar.
    Sadece aynı domain ve filtreleri geçen linkleri döner.
    max_links kadar benzersiz path döndürür.
    """
    links = []
    seen_paths = set()

    try:
        driver.get(base_url)
        # JS'in çalışması için biraz bekle
        time.sleep(1.5)

        anchors = driver.find_elements(By.TAG_NAME, "a")

        for a in anchors:
            href = a.get_attribute("href")
            if not href:
                continue

            cleaned = clean_and_filter_link(base_url, href, domain)
            if not cleaned:
                continue

            full_url, path = cleaned

            if path in seen_paths:
                continue

            seen_paths.add(path)
            links.append((full_url, path))

            if len(links) >= max_links:
                break

    except Exception:
        # Hata olursa o sayfayı pas geç
        return []

    random_sleep()
    return links


# ================== ASIL CRAWLER (Depth=2) ==================

def crawl_main_url(row):
    """
    Tek bir main_url satırı için:
      - Level 1: main_url'den MAX_FIRST_LEVEL_LINKS kadar link
      - Level 2: her Level 1 linkinden MAX_SECOND_LEVEL_LINKS kadar link
    Sonuçta satır listesi (dict) döner.
    """
    domain = row["domain"]
    main_url = row["main_url"]
    status = row.get("status", None)

    parsed_main = urlparse(main_url)
    base_domain = parsed_main.netloc
    if not base_domain:
        # Geçersiz URL
        return []

    path_tree_id = str(uuid.uuid4())
    results = []
    visited = set()  # aynı current_url'e tekrar gitmemek için

    driver = None
    try:
        driver = create_driver()

        # ---- LEVEL 1 (Depth = 1) ----
        first_level_links = extract_links_js(
            driver=driver,
            base_url=main_url,
            domain=base_domain,
            max_links=MAX_FIRST_LEVEL_LINKS
        )

        for full_url, path in first_level_links:
            if full_url in visited:
                continue
            visited.add(full_url)

            results.append({
                "domain": domain,
                "main_url": main_url,
                "parent_url": main_url,
                "current_url": full_url,
                "real_path": path,
                "depth": 1,
                "status": status,
                "path_tree_id": path_tree_id
            })

        # ---- LEVEL 2 (Depth = 2) ----
        for full_url_level1, path_level1 in first_level_links:
            second_level_links = extract_links_js(
                driver=driver,
                base_url=full_url_level1,
                domain=base_domain,
                max_links=MAX_SECOND_LEVEL_LINKS
            )

            for full_url2, path2 in second_level_links:
                if full_url2 in visited:
                    continue
                visited.add(full_url2)

                results.append({
                    "domain": domain,
                    "main_url": main_url,
                    "parent_url": full_url_level1,
                    "current_url": full_url2,
                    "real_path": path2,
                    "depth": 2,
                    "status": status,
                    "path_tree_id": path_tree_id
                })

    except Exception:
        pass
    finally:
        if driver is not None:
            try:
                driver.quit()
            except Exception:
                pass

    return results


# ================== ANA AKIŞ (CHECKPOINT'Lİ) ==================

# Girdi CSV'yi yükle
df = pd.read_csv(input_path)

# İlk 100lük test
if TEST_LIMIT is not None:
    df = df.head(TEST_LIMIT)

print(f"Toplam main_url sayısı (bu koşuda): {len(df)}")

# Eski output dosyalarını tekrar kullanmak istemiyorsan, manuel silmen iyi olur:
# os.remove(output_path)  # dikkat!
# os.remove(no_url_output_path)

buffer_results = []      # URL kayıtları için buffer
no_url_buffer = []       # URL üretemeyen main_url'ler için buffer

processed_main_urls = 0
total_urls_written = 0
total_no_url_domains = 0

def flush_buffers():
    """Ara kayıt: buffer'daki verileri CSV'lere append eder ve ekrana özet basar."""
    global buffer_results, no_url_buffer, total_urls_written, total_no_url_domains

    # URL'ler için
    if buffer_results:
        df_out = pd.DataFrame(buffer_results)
        file_exists = os.path.exists(output_path)
        df_out.to_csv(
            output_path,
            mode='a',
            index=False,
            header=not file_exists  # dosya yoksa header yaz
        )
        total_urls_written += len(df_out)
        buffer_results = []

    # URL üretemeyen domainler için
    if no_url_buffer:
        df_fail = pd.DataFrame(no_url_buffer)
        file_exists_fail = os.path.exists(no_url_output_path)
        df_fail.to_csv(
            no_url_output_path,
            mode='a',
            index=False,
            header=not file_exists_fail
        )
        total_no_url_domains += len(df_fail)
        no_url_buffer = []

    # Konsola bilgi
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] "
          f"Şu ana kadar işlenen main_url sayısı: {processed_main_urls} | "
          f"Toplam yazılan URL sayısı: {total_urls_written} | "
          f"Hiç URL üretemeyen domain sayısı: {total_no_url_domains}")


with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    future_to_meta = {}

    for idx, row in df.iterrows():
        future = executor.submit(crawl_main_url, row)
        future_to_meta[future] = {
            "idx": idx,
            "domain": row["domain"],
            "main_url": row["main_url"],
            "status": row.get("status", None)
        }

    for future in concurrent.futures.as_completed(future_to_meta):
        meta = future_to_meta[future]
        try:
            res = future.result()
        except Exception as e:
            print(f"[!] Thread hatası, satır {meta['idx']}: {e}")
            res = []

        processed_main_urls += 1

        if res:
            # URL üretenler
            buffer_results.extend(res)
        else:
            # Hiç URL üretemeyen main_url
            no_url_buffer.append({
                "domain": meta["domain"],
                "main_url": meta["main_url"],
                "status": meta["status"]
            })

        # Her CHECKPOINT_EVERY main_url'de bir ara kayıt
        if processed_main_urls % CHECKPOINT_EVERY == 0:
            flush_buffers()

# Döngü bittiğinde elde kalan buffer'ları da yaz
flush_buffers()

print("Tarama tamamlandı.")
print(f"Toplam yazılan URL sayısı: {total_urls_written}")
print(f"Toplam hiç URL üretemeyen main_url sayısı: {total_no_url_domains}")
print(f"URL'ler CSV: {output_path}")
print(f"URL üretemeyenler CSV: {no_url_output_path}")

Toplam main_url sayısı (bu koşuda): 100
[2025-11-16 16:41:07] Şu ana kadar işlenen main_url sayısı: 20 | Toplam yazılan URL sayısı: 286 | Hiç URL üretemeyen domain sayısı: 7
[2025-11-16 16:43:25] Şu ana kadar işlenen main_url sayısı: 40 | Toplam yazılan URL sayısı: 459 | Hiç URL üretemeyen domain sayısı: 15
[2025-11-16 16:48:00] Şu ana kadar işlenen main_url sayısı: 60 | Toplam yazılan URL sayısı: 750 | Hiç URL üretemeyen domain sayısı: 18
[2025-11-16 16:52:34] Şu ana kadar işlenen main_url sayısı: 80 | Toplam yazılan URL sayısı: 1033 | Hiç URL üretemeyen domain sayısı: 21
[2025-11-16 16:55:54] Şu ana kadar işlenen main_url sayısı: 100 | Toplam yazılan URL sayısı: 1285 | Hiç URL üretemeyen domain sayısı: 27
[2025-11-16 16:55:54] Şu ana kadar işlenen main_url sayısı: 100 | Toplam yazılan URL sayısı: 1285 | Hiç URL üretemeyen domain sayısı: 27
Tarama tamamlandı.
Toplam yazılan URL sayısı: 1285
Toplam hiç URL üretemeyen main_url sayısı: 27
URL'ler CSV: ./real_paths_depth2_vs2_selenium.csv
URL üretemeyenler CSV: ./no_urls_depth2_selenium.csv

In [1]:
!pip install playwright pandas
!python -m playwright install chromium

Requirement already satisfied: playwright in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (1.55.0)
Requirement already satisfied: pandas in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (2.3.3)
Requirement already satisfied: pyee<14,>=13 in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (from playwright) (13.0.0)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (from playwright) (3.2.4)
Requirement already satisfied: typing-extensions in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (from pyee<14,>=13->playwright) (4.15.0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\elifo\anacond3\envs\url_ai\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
!python -m playwright install chromium

In [5]:
!pip install playwright --upgrade --force-reinstall

Collecting playwright
  Downloading playwright-1.56.0-py3-none-win_amd64.whl.metadata (3.5 kB)
Collecting pyee<14,>=13 (from playwright)
  Using cached pyee-13.0.0-py3-none-any.whl.metadata (2.9 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright)
  Using cached greenlet-3.2.4-cp310-cp310-win_amd64.whl.metadata (4.2 kB)
Collecting typing-extensions (from pyee<14,>=13->playwright)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading playwright-1.56.0-py3-none-win_amd64.whl (35.6 MB)
   ---------------------------------------- 0.0/35.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/35.6 MB ? eta -:--:--
   - -------------------------------------- 1.3/35.6 MB 4.5 MB/s eta 0:00:08
   - -------------------------------------- 1.3/35.6 MB 4.5 MB/s eta 0:00:08
   -- ------------------------------------- 1.8/35.6 MB 2.6 MB/s eta 0:00:13
   -- ------------------------------------- 2.1/35.6 MB 2.4 MB/s eta 0:00:15
   -- ------------------------------------- 2.4/35.6 MB 2.1 MB/s eta 0:00:16
   -- ------------------------------------- 2.6/35.6 MB 2.1 MB/s eta 0:00:16
   --- ------------------------------------ 2.9/35.6 MB 1.8 MB/s eta 0:00:18
   --- ------------------------------------ 2.9/35.6 MB 1.8 MB/s eta 0:00:18
   --- ------------------------------------ 2.9/35.6 MB 1.8 MB/s eta 0:00:18
   --- ------------------------------------ 2.9/35.6 MB 1.8 MB/s eta 0:00:18
   --- ------------------------------------ 2.9/35.6 MB 1.8 MB/s eta 0:00:18
   --- ------------------------------------ 3.1/35.6 MB 1.1 MB/s eta 0:00:29
   --- ------------------------------------ 3.1/35.6 MB 1.1 MB/s eta 0:00:29
   --- ------------------------------------ 3.1/35.6 MB 1.1 MB/s eta 0:00:29
   --- ------------------------------------ 3.1/35.6 MB 1.1 MB/s eta 0:00:29
   --- ------------------------------------ 3.1/35.6 MB 1.1 MB/s eta 0:00:29
   --- ------------------------------------ 3.4/35.6 MB 894.7 kB/s eta 0:00:37
   --- ------------------------------------ 3.4/35.6 MB 894.7 kB/s eta 0:00:37
   --- ------------------------------------ 3.4/35.6 MB 894.7 kB/s eta 0:00:37
   ---- ----------------------------------- 3.7/35.6 MB 820.0 kB/s eta 0:00:39
   ---- ----------------------------------- 3.7/35.6 MB 820.0 kB/s eta 0:00:39
   ---- ----------------------------------- 3.7/35.6 MB 820.0 kB/s eta 0:00:39
   ---- ----------------------------------- 3.9/35.6 MB 788.2 kB/s eta 0:00:41
   ---- ----------------------------------- 3.9/35.6 MB 788.2 kB/s eta 0:00:41
   ---- ----------------------------------- 4.2/35.6 MB 774.4 kB/s eta 0:00:41
   ---- ----------------------------------- 4.2/35.6 MB 774.4 kB/s eta 0:00:41
   ----- ---------------------------------- 4.5/35.6 MB 769.2 kB/s eta 0:00:41
   ----- ---------------------------------- 4.7/35.6 MB 766.6 kB/s eta 0:00:41
   ----- ---------------------------------- 4.7/35.6 MB 766.6 kB/s eta 0:00:41
   ----- ---------------------------------- 5.0/35.6 MB 770.4 kB/s eta 0:00:40
   ----- ---------------------------------- 5.2/35.6 MB 775.6 kB/s eta 0:00:40
   ------ --------------------------------- 5.5/35.6 MB 783.9 kB/s eta 0:00:39
   ------ --------------------------------- 5.5/35.6 MB 783.9 kB/s eta 0:00:39
   ------ --------------------------------- 5.8/35.6 MB 791.7 kB/s eta 0:00:38
   ------ --------------------------------- 6.0/35.6 MB 798.9 kB/s eta 0:00:38
   ------- -------------------------------- 6.3/35.6 MB 807.2 kB/s eta 0:00:37
   ------- -------------------------------- 6.6/35.6 MB 818.3 kB/s eta 0:00:36
   ------- -------------------------------- 6.8/35.6 MB 827.3 kB/s eta 0:00:35
   ------- -------------------------------- 7.1/35.6 MB 837.2 kB/s eta 0:00:35
   -------- ------------------------------- 7.3/35.6 MB 849.9 kB/s eta 0:00:34
   -------- ------------------------------- 7.6/35.6 MB 860.4 kB/s eta 0:00:33
   -------- ------------------------------- 7.9/35.6 MB 870.4 kB/s eta 0:00:32
   --------- ------------------------------ 8.1/35.6 MB 881.5 kB/s eta 0:00:32
   --------- ------------------------------ 8.4/35.6 MB 893.6 kB/s eta 0:00:31
   ---------- ----------------------------- 8.9/35.6 MB 916.6 kB/s eta 0:00:30
   ---------- ----------------------------- 9.2/35.6 MB 927.6 kB/s eta 0:00:29
   ---------- ----------------------------- 9.7/35.6 MB 955.7 kB/s eta 0:00:28
   ----------- ---------------------------- 10.0/35.6 MB 969.9 kB/s eta 0:00:27
   ----------- ---------------------------- 10.5/35.6 MB 999.0 kB/s eta 0:00:26
   ------------ --------------------------- 11.0/35.6 MB 1.0 MB/s eta 0:00:24
   ------------- -------------------------- 11.8/35.6 MB 1.1 MB/s eta 0:00:23
   ------------- -------------------------- 12.3/35.6 MB 1.1 MB/s eta 0:00:22
   -------------- ------------------------- 13.1/35.6 MB 1.2 MB/s eta 0:00:20
   --------------- ------------------------ 13.9/35.6 MB 1.2 MB/s eta 0:00:19
   ---------------- ----------------------- 14.7/35.6 MB 1.2 MB/s eta 0:00:17
   ----------------- ---------------------- 15.5/35.6 MB 1.3 MB/s eta 0:00:16
   ------------------ --------------------- 16.5/35.6 MB 1.4 MB/s eta 0:00:15
   ------------------- -------------------- 17.6/35.6 MB 1.4 MB/s eta 0:00:13
   -------------------- ------------------- 18.6/35.6 MB 1.5 MB/s eta 0:00:12
   ---------------------- ----------------- 19.7/35.6 MB 1.5 MB/s eta 0:00:11
   ----------------------- ---------------- 21.0/35.6 MB 1.6 MB/s eta 0:00:10
   ------------------------- -------------- 22.3/35.6 MB 1.7 MB/s eta 0:00:08
   -------------------------- ------------- 23.6/35.6 MB 1.8 MB/s eta 0:00:07
   --------------------------- ------------ 24.9/35.6 MB 1.8 MB/s eta 0:00:06
   ----------------------------- ---------- 26.2/35.6 MB 1.9 MB/s eta 0:00:05
   ------------------------------ --------- 27.3/35.6 MB 2.0 MB/s eta 0:00:05
   -------------------------------- ------- 28.6/35.6 MB 2.0 MB/s eta 0:00:04
   --------------------------------- ------ 29.6/35.6 MB 2.1 MB/s eta 0:00:03
   ---------------------------------- ----- 30.9/35.6 MB 2.1 MB/s eta 0:00:03
   ------------------------------------ --- 32.2/35.6 MB 2.2 MB/s eta 0:00:02
   ------------------------------------- -- 33.3/35.6 MB 2.2 MB/s eta 0:00:02
   ---------------------------------------  34.9/35.6 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 35.6/35.6 MB 2.3 MB/s  0:00:15
Using cached greenlet-3.2.4-cp310-cp310-win_amd64.whl (298 kB)
Using cached pyee-13.0.0-py3-none-any.whl (15 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, greenlet, pyee, playwright

  Attempting uninstall: typing-extensions

    Found existing installation: typing_extensions 4.15.0

    Uninstalling typing_extensions-4.15.0:

   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
      Successfully uninstalled typing_extensions-4.15.0
   ---------------------------------------- 0/4 [typing-extensions]
  Attempting uninstall: greenlet
   ---------------------------------------- 0/4 [typing-extensions]
    Found existing installation: greenlet 3.2.4
   ---------------------------------------- 0/4 [typing-extensions]
   ---------- ----------------------------- 1/4 [greenlet]
    Uninstalling greenlet-3.2.4:
   ---------- ----------------------------- 1/4 [greenlet]
      Successfully uninstalled greenlet-3.2.4
   ---------- ----------------------------- 1/4 [greenlet]
   ---------- ----------------------------- 1/4 [greenlet]
   ---------- ----------------------------- 1/4 [greenlet]
  Attempting uninstall: pyee
   ---------- ----------------------------- 1/4 [greenlet]
    Found existing installation: pyee 13.0.0
   ---------- ----------------------------- 1/4 [greenlet]
    Uninstalling pyee-13.0.0:
   ---------- ----------------------------- 1/4 [greenlet]
      Successfully uninstalled pyee-13.0.0
   ---------- ----------------------------- 1/4 [greenlet]
   -------------------- ------------------- 2/4 [pyee]
  Attempting uninstall: playwright
   -------------------- ------------------- 2/4 [pyee]
    Found existing installation: playwright 1.55.0
   -------------------- ------------------- 2/4 [pyee]
    Uninstalling playwright-1.55.0:
   -------------------- ------------------- 2/4 [pyee]
   ------------------------------ --------- 3/4 [playwright]
      Successfully uninstalled playwright-1.55.0
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ---------------------------------------- 4/4 [playwright]

Successfully installed greenlet-3.2.4 playwright-1.56.0 pyee-13.0.0 typing-extensions-4.15.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyppeteer 2.0.0 requires pyee<12.0.0,>=11.0.0, but you have pyee 13.0.0 which is incompatible.
pyppeteer 2.0.0 requires urllib3<2.0.0,>=1.25.8, but you have urllib3 2.5.0 which is incompatible.

In [1]:
import playwright
print(playwright.__version__)

ModuleNotFoundError: No module named 'playwright'

In [2]:
import sys
print(sys.executable)

C:\Users\elifo\anacond3\envs\lungai\python.exe

In [3]:
import sys
!{sys.executable} -m pip install playwright --upgrade --force-reinstall

Collecting playwright
  Using cached playwright-1.56.0-py3-none-win_amd64.whl.metadata (3.5 kB)
Collecting pyee<14,>=13 (from playwright)
  Using cached pyee-13.0.0-py3-none-any.whl.metadata (2.9 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright)
  Using cached greenlet-3.2.4-cp310-cp310-win_amd64.whl.metadata (4.2 kB)
Collecting typing-extensions (from pyee<14,>=13->playwright)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Using cached playwright-1.56.0-py3-none-win_amd64.whl (35.6 MB)
Using cached greenlet-3.2.4-cp310-cp310-win_amd64.whl (298 kB)
Using cached pyee-13.0.0-py3-none-any.whl (15 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, greenlet, pyee, playwright

  Attempting uninstall: typing-extensions

    Found existing installation: typing_extensions 4.15.0

    Uninstalling typing_extensions-4.15.0:

   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
      Successfully uninstalled typing_extensions-4.15.0
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------- ----------------------------- 1/4 [greenlet]
   -------------------- ------------------- 2/4 [pyee]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ---------------------------------------- 4/4 [playwright]

Successfully installed greenlet-3.2.4 playwright-1.56.0 pyee-13.0.0 typing-extensions-4.15.0

  WARNING: The script playwright.exe is installed in 'C:\Users\elifo\anacond3\envs\lungai\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 2.2.6 which is incompatible.

In [2]:
import sys
print("Using Python:", sys.executable)
!{sys.executable} -m pip install playwright --upgrade --force-reinstall

Using Python: C:\Users\elifo\anacond3\envs\lungai\python.exe
Collecting playwright
  Using cached playwright-1.56.0-py3-none-win_amd64.whl.metadata (3.5 kB)
Collecting pyee<14,>=13 (from playwright)
  Using cached pyee-13.0.0-py3-none-any.whl.metadata (2.9 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright)
  Using cached greenlet-3.2.4-cp310-cp310-win_amd64.whl.metadata (4.2 kB)
Collecting typing-extensions (from pyee<14,>=13->playwright)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Using cached playwright-1.56.0-py3-none-win_amd64.whl (35.6 MB)
Using cached greenlet-3.2.4-cp310-cp310-win_amd64.whl (298 kB)
Using cached pyee-13.0.0-py3-none-any.whl (15 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, greenlet, pyee, playwright

  Attempting uninstall: typing-extensions

    Found existing installation: typing_extensions 4.15.0

    Uninstalling typing_extensions-4.15.0:

   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
   ---------------------------------------- 0/4 [typing-extensions]
      Successfully uninstalled typing_extensions-4.15.0
   ---------------------------------------- 0/4 [typing-extensions]
  Attempting uninstall: greenlet
   ---------------------------------------- 0/4 [typing-extensions]
    Found existing installation: greenlet 3.2.4
   ---------------------------------------- 0/4 [typing-extensions]
    Uninstalling greenlet-3.2.4:
   ---------------------------------------- 0/4 [typing-extensions]
      Successfully uninstalled greenlet-3.2.4
   ---------------------------------------- 0/4 [typing-extensions]
   ---------- ----------------------------- 1/4 [greenlet]
   ---------- ----------------------------- 1/4 [greenlet]
  Attempting uninstall: pyee
   ---------- ----------------------------- 1/4 [greenlet]
    Found existing installation: pyee 13.0.0
   ---------- ----------------------------- 1/4 [greenlet]
    Uninstalling pyee-13.0.0:
   ---------- ----------------------------- 1/4 [greenlet]
      Successfully uninstalled pyee-13.0.0
   ---------- ----------------------------- 1/4 [greenlet]
  Attempting uninstall: playwright
   ---------- ----------------------------- 1/4 [greenlet]
    Found existing installation: playwright 1.56.0
   ---------- ----------------------------- 1/4 [greenlet]
   ------------------------------ --------- 3/4 [playwright]
    Uninstalling playwright-1.56.0:
   ------------------------------ --------- 3/4 [playwright]
      Successfully uninstalled playwright-1.56.0
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ------------------------------ --------- 3/4 [playwright]
   ---------------------------------------- 4/4 [playwright]

Successfully installed greenlet-3.2.4 playwright-1.56.0 pyee-13.0.0 typing-extensions-4.15.0

  WARNING: The script playwright.exe is installed in 'C:\Users\elifo\anacond3\envs\lungai\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 2.2.6 which is incompatible.

In [1]:
import playwright
print(playwright.__version__)

AttributeError: module 'playwright' has no attribute '__version__'

In [2]:
import playwright
print(playwright)
print(playwright.__file__)

<module 'playwright' from 'C:\\Users\\elifo\\anacond3\\envs\\lungai\\lib\\site-packages\\playwright\\__init__.py'>
C:\Users\elifo\anacond3\envs\lungai\lib\site-packages\playwright\__init__.py

In [3]:
import pkg_resources
print(pkg_resources.get_distribution("playwright").version)

1.56.0

C:\Users\elifo\AppData\Local\Temp\ipykernel_21052\3254867211.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [4]:
from playwright.async_api import async_playwright

print("Playwright async API çalışıyor!")

Playwright async API çalışıyor!

In [5]:
import sys
!{sys.executable} -m playwright install chromium

Downloading Chromium 141.0.7390.37 (playwright build v1194) from https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1194/chromium-win64.zip
|                                                                                |   0% of 148.9 MiB
|â– â– â– â– â– â– â– â–                                                                         |  10% of 148.9 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                                 |  20% of 148.9 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                         |  30% of 148.9 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                 |  40% of 148.9 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                         |  50% of 148.9 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                 |  60% of 148.9 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                         |  70% of 148.9 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                 |  80% of 148.9 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–         |  90% of 148.9 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– | 100% of 148.9 MiB
Chromium 141.0.7390.37 (playwright build v1194) downloaded to C:\Users\elifo\anacond3\envs\lungai\lib\site-packages\playwright\driver\package\.local-browsers\chromium-1194
Downloading FFMPEG playwright build v1011 from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-win64.zip
|                                                                                |   0% of 1.3 MiB
|â– â– â– â– â– â– â– â–                                                                         |  10% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                                 |  20% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                         |  30% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                 |  40% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                         |  50% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                 |  60% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                         |  70% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                 |  81% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–         |  90% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– | 100% of 1.3 MiB
FFMPEG playwright build v1011 downloaded to C:\Users\elifo\anacond3\envs\lungai\lib\site-packages\playwright\driver\package\.local-browsers\ffmpeg-1011
Downloading Chromium Headless Shell 141.0.7390.37 (playwright build v1194) from https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1194/chromium-headless-shell-win64.zip
|                                                                                |   0% of 91 MiB
|â– â– â– â– â– â– â– â–                                                                         |  10% of 91 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                                 |  20% of 91 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                         |  30% of 91 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                 |  40% of 91 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                         |  50% of 91 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                 |  60% of 91 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                         |  70% of 91 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                 |  80% of 91 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–         |  90% of 91 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– | 100% of 91 MiB
Chromium Headless Shell 141.0.7390.37 (playwright build v1194) downloaded to C:\Users\elifo\anacond3\envs\lungai\lib\site-packages\playwright\driver\package\.local-browsers\chromium_headless_shell-1194
Downloading Winldd playwright build v1007 from https://cdn.playwright.dev/dbazure/download/playwright/builds/winldd/1007/winldd-win64.zip
|                                                                                |   1% of 0.1 MiB
|â– â– â– â– â– â– â– â–                                                                         |  10% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                                 |  24% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                         |  37% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                 |  49% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                 |  62% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                         |  75% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                 |  88% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– | 100% of 0.1 MiB
Winldd playwright build v1007 downloaded to C:\Users\elifo\anacond3\envs\lungai\lib\site-packages\playwright\driver\package\.local-browsers\winldd-1007

In [1]:
import pandas as pd

# Dosyayı yükle
df = pd.read_csv("real_paths_normal_playwright_final.csv")

# Sadece depth = 2 olanları filtrele
depth2_df = df[df["depth"] == 2]

# Sonuç
print("Depth = 2 olan URL sayısı:", len(depth2_df))

# İlk 10 örnek görmek istersen:
print(depth2_df.head(10))

Depth = 2 olan URL sayısı: 9470
    domain_id        domain                   main_url  \
5           4  facebook.com  https://www.facebook.com/
6           4  facebook.com  https://www.facebook.com/
7           4  facebook.com  https://www.facebook.com/
8           4  facebook.com  https://www.facebook.com/
9           4  facebook.com  https://www.facebook.com/
10          4  facebook.com  https://www.facebook.com/
11          4  facebook.com  https://www.facebook.com/
12          4  facebook.com  https://www.facebook.com/
13          4  facebook.com  https://www.facebook.com/
14          4  facebook.com  https://www.facebook.com/

                                           parent_url  \
5   https://www.facebook.com/recover/initiate/?pri...
6   https://www.facebook.com/recover/initiate/?pri...
7   https://www.facebook.com/recover/initiate/?pri...
8   https://www.facebook.com/recover/initiate/?pri...
9   https://www.facebook.com/recover/initiate/?pri...
10  https://www.facebook.com/recover/initiate/?pri...
11  https://www.facebook.com/recover/initiate/?pri...
12  https://www.facebook.com/recover/initiate/?pri...
13   https://www.facebook.com/r.php?entry_point=login
14   https://www.facebook.com/r.php?entry_point=login

                                          current_url  \
5                  https://www.facebook.com/login.php
6   https://www.facebook.com/login/identify/?ctx=r...
7                      https://www.facebook.com/lite/
8                     https://www.facebook.com/watch/
9   https://www.facebook.com/votinginformationcent...
10  https://www.facebook.com/privacy/policy/?entry...
11  https://www.facebook.com/privacy/center/?entry...
12  https://www.facebook.com/ad_campaign/landing.p...
13      https://www.facebook.com/help/637205020878504
14        https://www.facebook.com/legal/terms/update

                    real_path  depth  status  \
5                  /login.php      2   200.0
6            /login/identify/      2   200.0
7                      /lite/      2   200.0
8                     /watch/      2   200.0
9   /votinginformationcenter/      2   200.0
10           /privacy/policy/      2   200.0
11           /privacy/center/      2   200.0
12   /ad_campaign/landing.php      2   200.0
13      /help/637205020878504      2   200.0
14        /legal/terms/update      2   200.0

                            path_tree_id
5   2e891eb8-666f-4719-8ca0-e4c40c6d67af
6   2e891eb8-666f-4719-8ca0-e4c40c6d67af
7   2e891eb8-666f-4719-8ca0-e4c40c6d67af
8   2e891eb8-666f-4719-8ca0-e4c40c6d67af
9   2e891eb8-666f-4719-8ca0-e4c40c6d67af
10  2e891eb8-666f-4719-8ca0-e4c40c6d67af
11  2e891eb8-666f-4719-8ca0-e4c40c6d67af
12  2e891eb8-666f-4719-8ca0-e4c40c6d67af
13  2e891eb8-666f-4719-8ca0-e4c40c6d67af
14  2e891eb8-666f-4719-8ca0-e4c40c6d67af

In [2]:
summary = depth2_df.groupby("domain_id").size().reset_index(name="depth2_url_count")
print(summary.head(10))

   domain_id  depth2_url_count
0          1                11
1          2                 1
2          3                45
3          4                20
4          5                 5
5          6                33
6          9                10
7         14                42
8         15                26
9         17                 9

In [3]:
import pandas as pd

df = pd.read_csv("real_paths_normal_playwright_final.csv")

# Domain başına toplam path sayısı
domain_counts = (
    df.groupby("domain")["real_path"]
    .count()
    .reset_index(name="total_paths")
    .sort_values(by="total_paths", ascending=False)
)

print(domain_counts.head(20))   # ilk 20 domain

                 domain  total_paths
330            imdb.com           55
134         carwale.com           55
27          alibaba.com           55
162  cookiedatabase.org           50
436       microsoft.com           50
318         hubspot.com           50
74        atlassian.com           50
100        bikewale.com           49
491        nintendo.net           48
490        nintendo.com           48
322             ibm.com           48
496            nosv.org           47
483              nic.io           47
398        linkedin.com           47
279          genius.com           46
547     playstation.com           46
494           no-ip.com           46
626            sohu.com           45
214       dynatrace.com           44
651    steampowered.com           43

In [4]:
domain_counts_id = (
    df.groupby(["domain_id", "domain"])["real_path"]
    .count()
    .reset_index(name="total_paths")
    .sort_values(by="total_paths", ascending=False)
)

print(domain_counts_id.head(20))

     domain_id              domain  total_paths
110        153            imdb.com           55
146        202         alibaba.com           55
765       1139         carwale.com           55
271        383       atlassian.com           50
117        160         hubspot.com           50
197        276  cookiedatabase.org           50
2            3       microsoft.com           50
793       1193        bikewale.com           49
137        185             ibm.com           48
475        666        nintendo.net           48
657        932        nintendo.com           48
364        514              nic.io           47
744       1096            nosv.org           47
9           14        linkedin.com           47
423        593          genius.com           46
261        365     playstation.com           46
372        524           no-ip.com           46
175        246            sohu.com           45
279        393       dynatrace.com           44
394        559           ameblo.jp           43

In [5]:
depth_summary = (
    df.groupby(["domain", "depth"])["real_path"]
    .count()
    .reset_index()
    .pivot(index="domain", columns="depth", values="real_path")
    .fillna(0)
    .rename(columns={1: "depth1_count", 2: "depth2_count"})
)

depth_summary["total"] = depth_summary["depth1_count"] + depth_summary["depth2_count"]
depth_summary = depth_summary.sort_values(by="total", ascending=False)

print(depth_summary.head(20))

depth               depth1_count  depth2_count  total
domain
imdb.com                     5.0          50.0   55.0
carwale.com                  5.0          50.0   55.0
alibaba.com                  5.0          50.0   55.0
cookiedatabase.org           5.0          45.0   50.0
microsoft.com                5.0          45.0   50.0
hubspot.com                  5.0          45.0   50.0
atlassian.com                5.0          45.0   50.0
bikewale.com                 5.0          44.0   49.0
nintendo.net                 5.0          43.0   48.0
nintendo.com                 5.0          43.0   48.0
ibm.com                      5.0          43.0   48.0
nosv.org                     5.0          42.0   47.0
nic.io                       5.0          42.0   47.0
linkedin.com                 5.0          42.0   47.0
genius.com                   5.0          41.0   46.0
playstation.com              5.0          41.0   46.0
no-ip.com                    5.0          41.0   46.0
sohu.com                     5.0          40.0   45.0
dynatrace.com                5.0          39.0   44.0
steampowered.com             5.0          38.0   43.0

In [8]:
import pandas as pd

df = pd.read_csv("real_paths_normal_playwright_final.csv")
processed_domains = df['domain_id'].max()

print("İşlenen domain sayısı:", processed_domains)

İşlenen domain sayısı: 3103

In [9]:
import pandas as pd

# Giriş dosyası
input_path = "final_first_step_url.csv"

# Çıkış dosyaları
output1 = "final_part_1.csv"
output2 = "final_part_2.csv"

# CSV'yi yükle
df = pd.read_csv(input_path)

# Satır sayısı
n = len(df)
mid = n // 2   # tam ortadan böl

# İki parça oluştur
df_part1 = df.iloc[:mid]
df_part2 = df.iloc[mid:]

# Kaydet
df_part1.to_csv(output1, index=False)
df_part2.to_csv(output2, index=False)

print("Bölme tamamlandı!")
print(f"Toplam satır: {n}")
print(f"1. dosya: {len(df_part1)} satır")
print(f"2. dosya: {len(df_part2)} satır")

Bölme tamamlandı!
Toplam satır: 38705
1. dosya: 19352 satır
2. dosya: 19353 satır

In [1]:
import pandas as pd

# CSV dosyasını yükle
df = pd.read_csv("real_paths_normal_playwright_final.csv")

# Her main_url için üretilen URL sayısını hesapla
counts = df.groupby("main_url")["current_url"].count().reset_index(name="url_count")

# 8'den az URL üreten main_url'leri filtrele
low_producers = counts[counts["url_count"] < 9]

# Sonuçlar
num_main_urls = len(low_producers)              # Kaç main_url 8’den az üretmiş
total_urls_produced = low_producers["url_count"].sum()  # Toplam kaç URL üretmişler

print("8'den az URL üreten main_url sayısı:", num_main_urls)
print("Bu main_url'lerin ürettiği toplam URL sayısı:", total_urls_produced)

# İstersen detayları da görmek için:
low_producers.head()

8'den az URL üreten main_url sayısı: 5505
Bu main_url'lerin ürettiği toplam URL sayısı: 38750

                main_url  url_count
0        http://5ch.net/          2
1     http://abcvg.info/          2
2   http://adsafety.net/          2
3     http://akerala.in/          5
4  http://asilmedia.org/          8

In [2]:
import pandas as pd

# Ana dosyayı yükle
df = pd.read_csv("real_paths_normal_playwright_final.csv")

# Her main_url için üretilen URL sayısını hesapla
counts = df.groupby("main_url")["current_url"].count().reset_index(name="url_count")

# 8'den az URL üreten main_url'leri seç
low_producers = counts[counts["url_count"] < 8]

# Yeni CSV dosyasına kaydet
output_path = "low_producer_main_urls.csv"
low_producers.to_csv(output_path, index=False)

print(f"Toplam {len(low_producers)} main_url yeni dosyaya kaydedildi:")
print("→", output_path)

Toplam 1261 main_url yeni dosyaya kaydedildi:
→ low_producer_main_urls.csv

In [3]:
import pandas as pd

# Asıl dosyayı yükle
df = pd.read_csv("real_paths_normal_playwright_final.csv")

# Her main_url için path sayısını hesapla
count_df = df.groupby("main_url")["current_url"].count().reset_index(name="url_count")

# 8 veya daha az path üreten main_url'leri seç
low_main_urls = count_df[count_df["url_count"] <= 8]["main_url"].tolist()

# Asıl dataframe'den sadece bu main_url'lere ait satırları filtrele
filtered_df = df[df["main_url"].isin(low_main_urls)]

# Yeni CSV'ye kaydet
output_path = "paths_with_8_or_less.csv"
filtered_df.to_csv(output_path, index=False)

print(f"Toplam {len(filtered_df)} satır {output_path} dosyasına kaydedildi.")
print(f"Main_url sayısı: {len(low_main_urls)}")

Toplam 38750 satır paths_with_8_or_less.csv dosyasına kaydedildi.
Main_url sayısı: 5505

In [4]:
import pandas as pd

# Veriyi yükle
df = pd.read_csv("real_paths_normal_playwright_final.csv")

# Sadece depth = 2 olan satırları al
depth2_df = df[df["depth"] == 2]

# Her main_url için depth=2 path sayısını hesapla
depth2_count = depth2_df.groupby("main_url")["current_url"].count().reset_index(name="depth2_count")

# Sonuçları en çoktan en aza sırala
depth2_count = depth2_count.sort_values(by="depth2_count", ascending=False)

depth2_count.head()

                            main_url  depth2_count
6072        https://www.carwale.com/            50
5249        https://www.alibaba.com/            50
5886  https://www.boxofficemojo.com/            50
8089           https://www.imdb.com/            50
9881  https://www.pandasecurity.com/            50

In [6]:
import pandas as pd

# Veriyi yükle
df = pd.read_csv("real_paths_normal_playwright_final.csv")

# Sadece depth = 2 olan URL'leri filtrele
depth2_df = df[df["depth"] == 2]

# Her main_url için depth=2 olan URL sayısını hesapla
depth2_counts = depth2_df.groupby("main_url")["current_url"].count().reset_index(name="depth2_count")

# depth2_count > 9 olan main_url'leri seç
high_depth2 = depth2_counts[depth2_counts["depth2_count"] > 9]

# Sonuç
count_main_urls = len(high_depth2)

print("Depth=2 URL sayısı 9'dan fazla olan main_url sayısı:", count_main_urls)
high_depth2.head()

Depth=2 URL sayısı 9'dan fazla olan main_url sayısı: 4091

                    main_url  depth2_count
3   http://blog.esuteru.com/            11
4     http://blog.railsc.ru/            10
8       http://gece.az/chat/            12
10            http://gov.ru/            11
13        http://kremlin.ru/            17

In [13]:
import pandas as pd
import random

# CSV yükle
df = pd.read_csv("real_paths_normal_playwright_final.csv")

# Depth=2 olanlar
depth2 = df[df["depth"] == 2]

# Depth=2 sayısı > 9 olan main_url’ler
depth2_counts = depth2.groupby("main_url")["current_url"].count().reset_index()
valid_main_urls = depth2_counts[depth2_counts["current_url"] >= 8]["main_url"].tolist()

print("Depth=2 > 9 olan main_url sayısı:", len(valid_main_urls))

final_selected_rows = []

for main_url in valid_main_urls:
    sub = depth2[depth2["main_url"] == main_url]

    # Parent'e göre grupla
    parent_groups = {p: g for p, g in sub.groupby("parent_url")}

    selected = []

    # 1) Her parent_url’den 1 tane al → çeşitlilik maksimize
    for parent, g in parent_groups.items():
        selected.append(g.sample(1))
        if len(selected) == 8:
            break

    # 2) Eğer parent_url sayısı < 8 ise, rastgele tamamla
    if len(selected) < 8:
        remaining_needed = 8 - len(selected)

        # daha önce seçilmeyen depth2 pathlerden rastgele seç
        already_indices = pd.concat(selected).index
        pool = sub[~sub.index.isin(already_indices)]

        if len(pool) >= remaining_needed:
            extra = pool.sample(remaining_needed)
            selected.append(extra)
        else:
            selected.append(pool)

    # Sonuçları ekle
    final_selected_rows.append(pd.concat(selected))

# Nihai dataframe
final_df = pd.concat(final_selected_rows).reset_index(drop=True)

print("Toplam seçilen path sayısı:", len(final_df))

# CSV olarak kaydet
output_csv = "selected_diverse_depth2_paths.csv"
final_df.to_csv(output_csv, index=False)

print(f"\nCSV başarıyla kaydedildi → {output_csv}")

Depth=2 > 9 olan main_url sayısı: 4978
Toplam seçilen path sayısı: 39824

CSV başarıyla kaydedildi → selected_diverse_depth2_paths.csv

In [ ]:
import pandas as pd
import random

df = pd.read_csv("real_paths_normal_playwright_final.csv")

OUTPUT_SIZE = 8  # hedef path sayısı
final_rows = []

# Her main_url için
main_urls = df["main_url"].unique()

for main_url in main_urls:
    
    d1 = df[(df["main_url"] == main_url) & (df["depth"] == 1)]
    d2 = df[(df["main_url"] == main_url) & (df["depth"] == 2)]
    
    total_paths = len(d1) + len(d2)
    
    # ==========================================================
    # DURUM 1 — Toplam path 8’den az → Hepsini direkt al
    # ==========================================================
    if total_paths <= OUTPUT_SIZE:
        if total_paths > 0:
            final_rows.append(pd.concat([d1, d2]))
        continue  # bu main_url için daha seçim yapılmayacak
    
    # ==========================================================
    # DURUM 2 — Toplam path 8’den fazla → Akıllı seçime geç
    # ==========================================================
    
    selected = []
    
    # ---------- AŞAMA 1: Parent çeşitliliğini maksimize (depth 2) ----------
    parent_groups = {p: g for p, g in d2.groupby("parent_url")}
    
    for parent, group in parent_groups.items():
        selected.append(group.sample(1))  # her parent’tan 1 child
        if len(selected) == OUTPUT_SIZE:
            break
    
    # ---------- AŞAMA 2: Depth2 havuzundan rastgele ekle ----------
    if len(selected) < OUTPUT_SIZE and len(d2) > len(selected):
        
        already_idx = pd.concat(selected).index if selected else []
        remaining_d2 = d2[~d2.index.isin(already_idx)]
        
        need = OUTPUT_SIZE - len(selected)
        if len(remaining_d2) > 0:
            selected.append(remaining_d2.sample(min(len(remaining_d2), need)))
    
    # ---------- AŞAMA 3: Depth1 ile tamamla ----------
    if len(selected) < OUTPUT_SIZE:
        need = OUTPUT_SIZE - len(selected)
        if len(d1) > 0:
            selected.append(d1.sample(min(len(d1), need)))
    
    # Son seçilenleri birleştir
    if selected:
        final_rows.append(pd.concat(selected))


# Final output
final_df = pd.concat(final_rows).reset_index(drop=True)

print("Toplam seçilen path:", len(final_df))

output_path = "smart_selected_paths.csv"
final_df.to_csv(output_path, index=False)

print(f"Kaydedildi → {output_path}")

In [1]:
import pandas as pd
from tqdm import tqdm

print("CSV okunuyor...")
df = pd.read_csv("real_paths_normal_playwright_final.csv")
print("Toplam satır:", len(df))

# 1) Depth 2 olanlar
print("Depth 2 filtreleniyor...")
df_d2 = df[df["depth"] == 2]

# 2) Her main_url için depth 2 sayısı
print("Gruplama yapılıyor...")
depth2_counts = df_d2.groupby("main_url").size()

# 3) Depth=2 sayısı >= 9 olan main_url listesi
print("Koşulu sağlayan main_url bulunuyor...")
strong_domains = depth2_counts[depth2_counts >= 9].index.tolist()

print("Uygun main_url sayısı:", len(strong_domains))

# 4) Bu main_urllerden FULL satırları çekiyoruz
print("Sonuç satırları filtreleniyor...")
result_rows = df[df["main_url"].isin(strong_domains)]

print("Toplam seçilen satır:", len(result_rows))

# 5) CSV’ye kaydet
output_file = "selected_mainurls_depth2_over9.csv"
result_rows.to_csv(output_file, index=False)

print("Kayıt tamamlandı →", output_file)
print("İŞLEM BİTTİ ✔")

CSV okunuyor...
Toplam satır: 173483
Depth 2 filtreleniyor...
Gruplama yapılıyor...
Koşulu sağlayan main_url bulunuyor...
Uygun main_url sayısı: 4534
Sonuç satırları filtreleniyor...
Toplam seçilen satır: 98027
Kayıt tamamlandı → selected_mainurls_depth2_over9.csv
İŞLEM BİTTİ ✔

In [11]:
import pandas as pd
import numpy as np
import random

df = pd.read_csv("real_paths_normal_playwright_final.csv")
df["depth"] = pd.to_numeric(df["depth"], errors="coerce").fillna(0).astype(int)

print("Toplam satır:", len(df))
print("Toplam main_url:", df["main_url"].nunique())

Toplam satır: 173483
Toplam main_url: 13507

In [12]:
groups = {m: g for m, g in df.groupby("main_url")}
print("Hazır grup sayısı:", len(groups))

Hazır grup sayısı: 13507

In [13]:
OUTPUT_SIZE = 8

def fast_select(group):
    d1 = group[group["depth"] == 1]
    d2 = group[group["depth"] == 2]

    total = len(d1) + len(d2)

    # Eğer toplam path <= 8 ise direkt hepsini al
    if total <= OUTPUT_SIZE:
        return group

    selected = []

    # Aşama 1 — parent çeşitliliğini maksimize et
    parent_groups = list(d2.groupby("parent_url"))
    random.shuffle(parent_groups)

    for parent, grp in parent_groups:
        selected.append(grp.sample(1))
        if len(selected) == OUTPUT_SIZE:
            return pd.concat(selected)

    # Aşama 2 — depth2’den random doldur
    if len(selected) < OUTPUT_SIZE and len(d2) > 0:
        needed = OUTPUT_SIZE - len(selected)
        remaining = d2.loc[~d2.index.isin(pd.concat(selected).index)]
        if len(remaining) > 0:
            selected.append(
                remaining.sample(min(needed, len(remaining)))
            )

    # Aşama 3 — depth1’den tamamla
    combined = pd.concat(selected) if selected else pd.DataFrame()

    if len(combined) < OUTPUT_SIZE and len(d1) > 0:
        needed = OUTPUT_SIZE - len(combined)
        selected_d1 = d1.sample(min(needed, len(d1)))
        combined = pd.concat([combined, selected_d1])

    return combined

In [14]:
final_list = []

for main_url, group in groups.items():
    final_list.append(fast_select(group))

final_df = pd.concat(final_list).reset_index(drop=True)

print("Toplam seçilen path:", len(final_df))

Toplam seçilen path: 102766

In [15]:
final_df.to_csv("smart_selected_paths.csv", index=False)
print("Kaydedildi → smart_selected_paths.csv")

Kaydedildi → smart_selected_paths.csv

In [16]:
import pandas as pd

# Ana dosyayı oku
df = pd.read_csv("smart_selected_paths.csv")

# Her main_url için toplam path sayısı
counts = (
    df.groupby("main_url")
      .size()
      .reset_index(name="total_paths")
      .sort_values("total_paths", ascending=False)
)

# Kaydet
output_path = "main_url_path_counts.csv"
counts.to_csv(output_path, index=False)

print("✔ main_url path sayıları kaydedildi →", output_path)
print("Toplam unique main_url:", len(counts))
counts.head()

✔ main_url path sayıları kaydedildi → main_url_path_counts.csv
Toplam unique main_url: 13507

                          main_url  total_paths
13506           https://zvelo.com/            8
13465           https://zaxid.net/            8
13466           https://zbato.com/            8
13468          https://zeduva.com/            8
13469  https://zehra-ogretmen.com/            8

In [1]:
import pandas as pd

df = pd.read_csv("smart_selected_paths.csv")

print("Toplam satır:", len(df))

# ---- 1) Tam satır duplicate kontrolü ----
full_dupes = df[df.duplicated()]
print("Tam satır duplicate sayısı:", len(full_dupes))

# ---- 2) current_url bazlı duplicate ----
cur_dupes = df[df.duplicated(subset=["current_url"])]
print("current_url duplicate sayısı:", len(cur_dupes))

# ---- 3) main_url + current_url kombinasyonu ----
combo_dupes = df[df.duplicated(subset=["main_url", "current_url"])]
print("main_url + current_url duplicate sayısı:", len(combo_dupes))

# Eğer duplicate varsa kaydedelim
if len(full_dupes) > 0:
    full_dupes.to_csv("duplicates_full_rows.csv", index=False)
    print("Tam satır duplicate → duplicates_full_rows.csv olarak kaydedildi")

if len(cur_dupes) > 0:
    cur_dupes.to_csv("duplicates_current_url.csv", index=False)
    print("current_url duplicate → duplicates_current_url.csv olarak kaydedildi")

if len(combo_dupes) > 0:
    combo_dupes.to_csv("duplicates_main_current.csv", index=False)
    print("main_url + current_url duplicate → duplicates_main_current.csv olarak kaydedildi")

Toplam satır: 102766
Tam satır duplicate sayısı: 0
current_url duplicate sayısı: 1549
main_url + current_url duplicate sayısı: 0
current_url duplicate → duplicates_current_url.csv olarak kaydedildi

In [2]:
df = pd.read_csv("C:/Users/elifo/Bitirme_Projesi_Dataset_Olusturma/smart_selected_paths.csv")
df.head(20)

,domain_id,domain,main_url,parent_url,current_url,real_path,depth,status,path_tree_id
0,2331,5ch.net,http://5ch.net/,http://5ch.net/,http://5ch.net/_login,/_login,1,200.0,fa62d80c-bd40-4618-a671-5d15b5cf6658
1,2331,5ch.net,http://5ch.net/,http://5ch.net/,http://5ch.net/faq.html,/faq.html,1,200.0,fa62d80c-bd40-4618-a671-5d15b5cf6658
2,15950,abcvg.info,http://abcvg.info/,http://abcvg.info/,http://abcvg.info/speedtest/,/speedtest/,1,200.0,e72eade4-ef2b-4dbb-ae12-ddcbed3c4dc8
3,15950,abcvg.info,http://abcvg.info/,http://abcvg.info/,http://abcvg.info/doge/,/doge/,1,200.0,e72eade4-ef2b-4dbb-ae12-ddcbed3c4dc8
4,15962,adsafety.net,http://adsafety.net/,http://adsafety.net/,http://adsafety.net/privacy.html,/privacy.html,1,200.0,5b28921a-c2b8-487c-acf5-636f6b019ec1
5,15962,adsafety.net,http://adsafety.net/,http://adsafety.net/privacy.html,http://adsafety.net/optout.html,/optout.html,2,200.0,5b28921a-c2b8-487c-acf5-636f6b019ec1
6,6528,akerala.in,http://akerala.in/,http://akerala.in/,http://akerala.in/store/apps/category/ENTERTAI...,/store/apps/category/ENTERTAINMENT,1,200.0,beb6e081-89d4-44f6-a8d7-51b75782e49a
7,6528,akerala.in,http://akerala.in/,http://akerala.in/,http://akerala.in/store/apps/datasafety?id=uk....,/store/apps/datasafety,1,200.0,beb6e081-89d4-44f6-a8d7-51b75782e49a
8,6528,akerala.in,http://akerala.in/,http://akerala.in/,http://akerala.in/store/pass/getstarted,/store/pass/getstarted,1,200.0,beb6e081-89d4-44f6-a8d7-51b75782e49a
9,6528,akerala.in,http://akerala.in/,http://akerala.in/,http://akerala.in/store/points/enroll,/store/points/enroll,1,200.0,beb6e081-89d4-44f6-a8d7-51b75782e49a
10,6528,akerala.in,http://akerala.in/,http://akerala.in/,http://akerala.in/redeem,/redeem,1,200.0,beb6e081-89d4-44f6-a8d7-51b75782e49a
11,14535,asilmedia.org,http://asilmedia.org/,http://asilmedia.org/,http://asilmedia.org/index.php?do=lostpassword,/index.php,1,200.0,9f36204b-67fb-4121-be3f-7941056a2be7
12,14535,asilmedia.org,http://asilmedia.org/,http://asilmedia.org/,http://asilmedia.org/whatchnow.html,/whatchnow.html,1,200.0,9f36204b-67fb-4121-be3f-7941056a2be7
13,14535,asilmedia.org,http://asilmedia.org/,http://asilmedia.org/,http://asilmedia.org/popular.html,/popular.html,1,200.0,9f36204b-67fb-4121-be3f-7941056a2be7
14,14535,asilmedia.org,http://asilmedia.org/,http://asilmedia.org/,http://asilmedia.org/lastnews/,/lastnews/,1,200.0,9f36204b-67fb-4121-be3f-7941056a2be7
15,14535,asilmedia.org,http://asilmedia.org/,http://asilmedia.org/,http://asilmedia.org/films/tarjima_kinolar/,/films/tarjima_kinolar/,1,200.0,9f36204b-67fb-4121-be3f-7941056a2be7
16,14535,asilmedia.org,http://asilmedia.org/,http://asilmedia.org/index.php?do=lostpassword,http://asilmedia.org/films/zarfilm/,/films/zarfilm/,2,200.0,9f36204b-67fb-4121-be3f-7941056a2be7
17,14535,asilmedia.org,http://asilmedia.org/,http://asilmedia.org/index.php?do=lostpassword,http://asilmedia.org/films/rusfilm/,/films/rusfilm/,2,200.0,9f36204b-67fb-4121-be3f-7941056a2be7
18,14535,asilmedia.org,http://asilmedia.org/,http://asilmedia.org/index.php?do=lostpassword,http://asilmedia.org/films/premyera/,/films/premyera/,2,200.0,9f36204b-67fb-4121-be3f-7941056a2be7
19,7796,asurahosting.com,http://asurahosting.com/index,http://asurahosting.com/index,http://asurahosting.com/hosting,/hosting,1,200.0,cc9f2951-7e24-46b4-a5ff-9793dc31f143

In [1]:
import pandas as pd

# CSV dosyasını yükle
df = pd.read_csv("real_paths_normal_playwright_final_3.csv")

# Her main_url için kaç URL üretildiğini hesapla
counts = df.groupby("main_url")["current_url"].count()

# Her domain için: min(actual, 8)
limited_counts = counts.apply(lambda x: min(x, 8))

# Toplam elde edilen URL sayısı
total_urls = limited_counts.sum()

print("Toplam ana URL sayısı:", len(counts))
print("Toplam URL (8'e sabitlenmiş):", total_urls)

Toplam ana URL sayısı: 15727
Toplam URL (8'e sabitlenmiş): 119181

In [16]:
import pandas as pd

# Ana dosya
input_path = r"Lutfen_son_domain_olsun_1.csv"

# Dosyayı yükle
df = pd.read_csv(input_path, header=None, names=["domain"])

# Satır sayısı
total = len(df)
half = total // 2   # tam yarısını alır

print(f"Toplam domain: {total}")
print(f"Her parça yaklaşık: {half}")

# İkiye böl
df_first = df.iloc[:half]
df_second = df.iloc[half:]

# Kayıt
df_first.to_csv("Lutfen_son_domain_olsun_1_part1.csv", index=False, header=False)
df_second.to_csv("Lutfen_son_domain_olsun_1_part2.csv", index=False, header=False)

print("Bölme işlemi tamamlandı!")
print("Kaydedilen dosyalar:")
print(" - Lutfen_son_domain_olsun_1_part1.csv")
print(" - Lutfen_son_domain_olsun_1_part2.csv")

Toplam domain: 59125
Her parça yaklaşık: 29562
Bölme işlemi tamamlandı!
Kaydedilen dosyalar:
 - Lutfen_son_domain_olsun_1_part1.csv
 - Lutfen_son_domain_olsun_1_part2.csv

In [13]:
import pandas as pd

df = pd.read_csv("domain_scan_results_part1.csv")

# İlk 555 satır
df_1555 = df.head(29465)

# main_url boş olanları say
empty_count = df_1555["main_url"].isna().sum() + (df_555["main_url"].astype(str).str.strip() == "").sum()

print("İlk 555 satırda boş main_url sayısı:", empty_count)

İlk 555 satırda boş main_url sayısı: 7060